### ISSUE TITLE
"npm run production" results in error

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1588]
After running "npm install", I tried "npm run production" but this fails with:

```
> gifsicle@3.0.4 postinstall /webtrees-2.0/node_modules/gifsicle
> node lib/install.js

internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at /webtrees-2.0/node_modules/bin-check/index.js:22:12
    at /webtrees-2.0/node_modules/executable/index.js:27:4
    at FSReqWrap.oncomplete (fs.js:153:5)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@3.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-22T10_27_54_004Z-debug.log

```

**Comment by fisharebest** [comment]
I just tried a clean build, which worked OK.

```
$ rm -Rf node_modules
$ npm install
$ npm run production
```

Does it help if you run `npm cache clean`?

**Comment by magicsunday** [comment]
No does not help. Same error. I'm using Debian 9. NPM v8.9.4.

**Comment by magicsunday** [comment]
Got it. My webtrees instance lies on a Raid drive on my NAS.

Found this: https://github.com/sass/node-sass/issues/1407#issuecomment-255406068

After adding "exec" to the /etc/fstab of the Raid config, rebooting, the command "npm install" and "npm run production" run just fine.
