### ISSUE TITLE
Admin / User administration link gives 500 error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1889]
[Mon Sep 03 13:58:25.250440 2018] [php7:error] [pid 997] [client 192.168.1.101:59352] PHP Fatal error:  Uncaught TypeError: Return value of Fisharebest\\Webtrees\\User::getPreference() must be of the type string, integer returned in /var/www/app/User.php:540\nStack trace:\n#0 /var/www/app/Http/Controllers/AdminUsersController.php(125): Fisharebest\\Webtrees\\User->getPreference(' admin_users_pa...', 10)\n#1 [internal function]: Fisharebest\\Webtrees\\Http\\Controllers\\AdminUsersController->index(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Fisharebest\\Webtrees\\User))\n#2 /var/www/app/Resolver.php(85): ReflectionMethod->invoke(Object(Fisharebest\\Webtrees\\Http\\Controllers\\AdminUsersController), Object(Symfony\\Component\\HttpFoundation\\Request), Object(Fisharebest\\Webtrees\\User))\n#3 /var/www/index.php(324): Fisharebest\\Webtrees\\Resolver->dispatch(Object(Fisharebest\\Webtrees\\Http\\Controllers\\AdminUsersController), 'index')\n#4 /var/www/app/Http/Middleware/CheckForMaintenanceMode.php(48): Fisharebest\\Webtrees\\{closure}(Object(Symfony\\Component\\HttpFoundation\\Request))\n#5 /var/www/index.php(319): Fisharebest\\Webtrees\\ in /var/www/app/User.php on line 540, referer: http://192.168.1.110/index.php?route=admin-control-panel

**Comment by fisharebest** [comment]
> force default value to be string too

The return value from the database will always be a string, so the default should also be a string.

We can cast to int/bool afterwards.
