### ISSUE TITLE
New User Registration Validation Error

### ISSUE THREAD

**Issue by ricklach** [fisharebest/webtrees#1908]
The following error was generated when trying to validate a new user request from the link in the validation email: Fatal error: Uncaught Error: Call to a member function getPreference() on null in /home/lacharite/lacharite.ca/app/Http/Controllers/Auth/VerifyEmailController.php:55 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Http\Controllers\Auth\VerifyEmailController->verify(Object(Symfony\Component\HttpFoundation\Request), Object(Fisharebest\Webtrees\Tree)) #1 /home/lacharite/lacharite.ca/app/Resolver.php(85): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\Auth\VerifyEmailController), Object(Symfony\Component\HttpFoundation\Request), Object(Fisharebest\Webtrees\Tree)) #2 /home/lacharite/lacharite.ca/index.php(324): Fisharebest\Webtrees\Resolver->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\Auth\VerifyEmailController), 'verify') #3 /home/lacharite/lacharite.ca/app/Http/Middleware/CheckForMaintenanceMode.php(48): Fisharebest\Webtrees\{closure}(Object(Symfony\Component\HttpFoundation\Request)) #4 /home/lacharite/lacharite.ca/index.php(319): Fisharebest\Webtrees\Http\Middleware\CheckForMainten in /home/lacharite/lacharite.ca/app/Http/Controllers/Auth/VerifyEmailController.php on line 55

**Comment by fisharebest** [comment]
This code is trying to send an email to the "genealogy" contact for the tree.

You haven't set one, which causes the error.

So, a temporary workaround is to set a genealogy contact.
