### ISSUE TITLE
2.0 - Pedigree chart gets spin icon

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1922]
[Sun Sep 23 07:54:01.141405 2018] [php7:error] [pid 12518] [client ::1:54968] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Fisharebest\\Webtrees\\Http\\Controllers\\PedigreeChartController::Fisharebest\\Webtrees\\Http\\Controllers\\{closure}() must be an instance of Fisharebest\\Webtrees\\Individual, null given in /var/www/app/Http/Controllers/PedigreeChartController.php:149\nStack trace:\n#0 [internal function]: Fisharebest\\Webtrees\\Http\\Controllers\\PedigreeChartController->Fisharebest\\Webtrees\\Http\\Controllers\\{closure}(NULL)\n#1 /var/www/app/Http/Controllers/PedigreeChartController.php(155): array_map(Object(Closure), Array)\n#2 [internal function]: Fisharebest\\Webtrees\\Http\\Controllers\\PedigreeChartController->chart(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Fisharebest\\Webtrees\\Tree))\n#3 /var/www/app/Resolver.php(85): ReflectionMethod->invoke(Object(Fisharebest\\Webtrees\\Http\\Controllers\\PedigreeChartController), Object(Symfony\\Component\\HttpFoundation\\Request), Object(Fisharebest\\Webtrees\\Tree))\n#4 /var/www/index.php(321): Fisharebest\\Webtrees\\Resolver->dispatch(Object(Fisharebest\\Web in /var/www/app/Http/Controllers/PedigreeChartController.php on line 149, referer: http://localhost/index.php?route=pedigree&xref=I0001&ged=tree1

**Comment by makitso** [comment]
To get this error select an individual and then select the Pedigree chart from the drop-down.
