### ISSUE TITLE
2.0 - 500 error when trying to export Geographical Data

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1935]
[Thu Sep 27 09:44:38.282595 2018] [php7:error] [pid 13353] [client ::1:34706] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Fisharebest\\Webtrees\\Http\\Controllers\\AdminLocationController::buildLevel() must be of the type integer, string given, called in /var/www/app/Http/Controllers/AdminLocationController.php on line 675 and defined in /var/www/app/Http/Controllers/AdminLocationController.php:662\nStack trace:\n#0 /var/www/app/Http/Controllers/AdminLocationController.php(675): Fisharebest\\Webtrees\\Http\\Controllers\\AdminLocationController->buildLevel('327', Array, Array)\n#1 /var/www/app/Http/Controllers/AdminLocationController.php(264): Fisharebest\\Webtrees\\Http\\Controllers\\AdminLocationController->buildLevel(0, Array, Array)\n#2 [internal function]: Fisharebest\\Webtrees\\Http\\Controllers\\AdminLocationController->exportLocations(Object(Symfony\\Component\\HttpFoundation\\Request))\n#3 /var/www/app/Resolver.php(85): ReflectionMethod->invoke(Object(Fisharebest\\Webtrees\\Http\\Controllers\\AdminLocationController), Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 /var/www/index.php(321): Fisharebest\\W in /var/www/app/Http/Controllers/AdminLocationController.php on line 662, referer: http://localhost/index.php?route=map-data

**Comment by makitso** [comment]
This happens at the top level.  If you go down a few levels it will then work.

![image](https://user-images.githubusercontent.com/5147603/46161500-90ead180-c23a-11e8-8bf9-ed0de08adab5.png)
