### ISSUE TITLE
2.0 - Latest update results in 500 error on login

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1943]
Fatal error: Uncaught TypeError: Return value of Fisharebest\Webtrees\Site::getPreference() must be of the type string, integer returned in /var/www/app/Site.php:50 Stack trace: #0 /var/www/app/Services/UpgradeService.php(94): Fisharebest\Webtrees\Site::getPreference('LATEST_WT_VERSI...') #1 /var/www/app/Services/UpgradeService.php(62): Fisharebest\Webtrees\Services\UpgradeService->fetchLatestVersion() #2 /var/www/app/Http/Controllers/Auth/LoginController.php(116): Fisharebest\Webtrees\Services\UpgradeService->latestVersion() #3 [internal function]: Fisharebest\Webtrees\Http\Controllers\Auth\LoginController->loginAction(Object(Symfony\Component\HttpFoundation\Request), Object(Fisharebest\Webtrees\Services\UpgradeService), NULL) #4 /var/www/app/Resolver.php(87): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\Auth\LoginController), Object(Symfony\Component\HttpFoundation\Request), Object(Fisharebest\Webtrees\Services\UpgradeService), NULL) #5 /var/www/index.php(323): Fisharebest\Webtrees\Resolver->dis in /var/www/app/Site.php on line 50

**Comment by makitso** [comment]
Sorry, rsync error
