### ISSUE TITLE
Linking a child to an existing family gives error - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1991]
I try to link X5906 as a child in test to F878. I get Fatal error.               

Fatal error: Uncaught TypeError: Argument 1 passed to   Fisharebest\Webtrees\GedcomRecord::updateFact() must be of the type string,   null given, called in /home/amitys/test.amitys.com/app/Http/Controllers/EditIndividualController.php   on line 718 and defined in   /home/amitys/test.amitys.com/app/GedcomRecord.php:1246 Stack trace: #0   /home/amitys/test.amitys.com/app/Http/Controllers/EditIndividualController.php(718):   Fisharebest\Webtrees\GedcomRecord->updateFact(NULL, '1 FAMC @F878@', true)   #1 [internal function]:   Fisharebest\Webtrees\Http\Controllers\EditIndividualController->linkChildToFamilyAction(Object(Symfony\Component\HttpFoundation\Request),   Object(Fisharebest\Webtrees\Tree)) #2   /home/amitys/test.amitys.com/app/Resolver.php(87):   ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\EditIndividualController),   Object(Symfony\Component\HttpFoundation\Request),   Object(Fisharebest\Webtrees\Tree)) #3   /home/amitys/test.amitys.com/index.php(326):   Fisharebest\Webtrees\Resolver->dispatch(Object(Fisharebest\Webtrees in   /home/amitys/test.amitys.com/app/GedcomRecord.php on line 1246

**Comment by melizaa** [comment]
I do not yet manage to link a child to an existing family.

**Comment by melizaa** [comment]
Now it works OK
