### ISSUE TITLE
2.0 Fatal error: My page - add favourites

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#2034]
1) radio button "URL": usefullness?
2) select radio buttton 'URL' -> input something and press enter leads to:

Fatal error: Uncaught TypeError: Argument 1 passed to Fisharebest\Webtrees\GedcomRecord::getInstance() must be of the type string, null given, called in /home/webtrees/dev.webtrees.net/demo-dev/app/Module/UserFavoritesModule.php on line 164 and defined in /home/webtrees/dev.webtrees.net/demo-dev/app/GedcomRecord.php:145 Stack trace: #0 /home/webtrees/dev.webtrees.net/demo-dev/app/Module/UserFavoritesModule.php(164): Fisharebest\Webtrees\GedcomRecord::getInstance(NULL, Object(Fisharebest\Webtrees\Tree)) #1 /home/webtrees/dev.webtrees.net/demo-dev/app/Module/UserFavoritesModule.php(71): Fisharebest\Webtrees\Module\UserFavoritesModule->getFavorites(Object(Fisharebest\Webtrees\Tree), Object(Fisharebest\Webtrees\User)) #2 /home/webtrees/dev.webtrees.net/demo-dev/resources/views/user-page-block.phtml(5): Fisharebest\Webtrees\Module\UserFavoritesModule->getBlock(Object(Fisharebest\Webtrees\Tree), 61) #3 /home/webtrees/dev.webtrees.net/demo-dev/app/View.php(140): include('/home/webtrees/...') #4 /home/webtrees/dev.webtrees.net/de in /home/webtrees/dev.webtrees.net/demo-dev/app/GedcomRecord.php on line 145

**Comment by ungeahnt** [comment]
> radio button "URL": usefullness?
Yes, it's useful!
