### ISSUE TITLE
Fatal error when I try to enter test systems - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2037]
I get

Fatal error: Uncaught Error: Call to undefined method Fisharebest\Webtrees\Fact::getAttribute() in /home/amitys/test.amitys.com/app/Module/ResearchTaskModule.php:89 Stack trace: #0 /home/amitys/test.amitys.com/resources/views/tree-page-block.phtml(5): Fisharebest\Webtrees\Module\ResearchTaskModule->getBlock(Object(Fisharebest\Webtrees\Tree), 428) #1 /home/amitys/test.amitys.com/app/View.php(140): include('/home/amitys/te...') #2 /home/amitys/test.amitys.com/app/View.php(184): Fisharebest\Webtrees\View->render() #3 /home/amitys/test.amitys.com/app/Helpers/functions.php(84): Fisharebest\Webtrees\View::make('tree-page-block', Array) #4 /home/amitys/test.amitys.com/resources/views/tree-page.phtml(11): view('tree-page-block', Array) #5 /home/amitys/test.amitys.com/app/View.php(140): include('/home/amitys/te...') #6 /home/amitys/test.amitys.com/app/View.php(184): Fisharebest\Webtrees\View->render() #7 /home/amitys/test.amitys.com/app/Helpers/functions.php(84): Fisharebest\Webtrees\View::make('tree-page', Array) #8 /home/amitys/ in /home/amitys/test.amitys.com/app/Module/ResearchTaskModule.php on line 89

**Comment by melizaa** [comment]
The code is updated to dc11b3a38.
