### ISSUE TITLE
Link media objects to facts and events returns an empty table - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2038]
DataTables warning: table id=DataTable_0 - inbvalid JSON response.

**Comment by fisharebest** [comment]
There will be an error message in the AJAX request.

Is this error on a site that I can access?

**Comment by melizaa** [comment]
I see this in the test system.

Fatal error: Uncaught Error: Call to undefined method Fisharebest\Webtrees\Fact::getFactId() in /home/amitys/test.amitys.com/resources/views/admin/fix-level-0-media-action.phtml:6 Stack trace: #0 /home/amitys/test.amitys.com/app/View.php(140): include() #1 /home/amitys/test.amitys.com/app/View.php(184): Fisharebest\Webtrees\View->render() #2 /home/amitys/test.amitys.com/app/Helpers/functions.php(84): Fisharebest\Webtrees\View::make('admin/fix-level...', Array) #3 /home/amitys/test.amitys.com/app/Http/Controllers/AdminController.php(520): view('admin/fix-level...', Array) #4 [internal function]: Fisharebest\Webtrees\Http\Controllers\AdminController->Fisharebest\Webtrees\Http\Controllers\{closure}(Object(Fisharebest\Webtrees\Fact)) #5 /home/amitys/test.amitys.com/app/Http/Controllers/AdminController.php(522): array_map(Object(Closure), Array) #6 [internal function]: Fisharebest\Webtrees\Http\Controllers\AdminController->Fisharebest\Webtrees\Http\Controllers\{closure}(Object(stdClass)) #7 /home/amitys/test.amitys.com/app/Htt in /home/amitys/test.amitys.com/resources/views/admin/fix-level-0-media-action.phtml on line 6
