### ISSUE TITLE
2.0 - Demo site throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2374]

**Comment by makitso** [comment]
#0 …/vendor/illuminate/container/Container.php(800): Illuminate\Container\Container->notInstantiable('Psr\\Http\\Messag...')
#1 …/vendor/illuminate/container/Container.php(671): Illuminate\Container\Container->build('Psr\\Http\\Messag...')
#2 …/vendor/illuminate/container/Container.php(619): Illuminate\Container\Container->resolve('Psr\\Http\\Messag...', Array)
#3 …/app/Helpers/functions.php(42): Illuminate\Container\Container->make('Psr\\Http\\Messag...')
#4 …/resources/views/layouts/default.phtml(71): app('Psr\\Http\\Messag...')
#5 …/app/View.php(190): include('/home/webtrees/...')
#6 …/app/View.php(284): Fisharebest\Webtrees\View->render()
#7 …/app/Helpers/functions.php(175): Fisharebest\Webtrees\View::make('layouts/default', Array)
#8 …/app/Http/Controllers/AbstractBaseController.php(49): view('layouts/default', Array)
#9 …/app/Http/Controllers/ErrorController.php(119): Fisharebest\Webtrees\Http\Controllers\AbstractBaseController->viewResponse('errors/unhandle...', Array, 500)
#10 …/app/Http/Middleware/ExceptionHandler.php(63): Fisharebest\Webtrees\Http\Controllers\ErrorController->unhandledExceptionResponse(Object(Fisharebest\Webtrees\Http\Request), Object(ErrorException))
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ExceptionHandler->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#13 …/index.php(109): Middleland\Dispatcher->dispatch(Object(Fisharebest\Webtrees\Http\Request))
#14 {main}

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Psr\Http\Message\ServerRequestInterface] is not instantiable. in /home/webtrees/dev.webtrees.net/demo-dev/vendor/illuminate/container/Container.php:962 Stack trace: #0 /home/webtrees/dev.webtrees.net/demo-dev/vendor/illuminate/container/Container.php(800): Illuminate\Container\Container->notInstantiable('Psr\\Http\\Messag...') #1 /home/webtrees/dev.webtrees.net/demo-dev/vendor/illuminate/container/Container.php(671): Illuminate\Container\Container->build('Psr\\Http\\Messag...') #2 /home/webtrees/dev.webtrees.net/demo-dev/vendor/illuminate/container/Container.php(619): Illuminate\Container\Container->resolve('Psr\\Http\\Messag...', Array) #3 /home/webtrees/dev.webtrees.net/demo-dev/app/Helpers/functions.php(42): Illuminate\Container\Container->make('Psr\\Http\\Messag...') #4 /home/webtrees/dev.webtrees.net/demo-dev/app/Session.php(132): app('Psr\\Http\\Messag...') #5 /home/webtrees/dev.webtrees.net/demo-dev/app/Session.php(77): Fishare in /home/webtrees/dev.webtrees.net/demo-dev/vendor/illuminate/container/Container.php on line 962
