### ISSUE TITLE
2.0 - Edit user throws error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2389]
Control Panel / User administration/  then select Edit then do a save and:
Undefined index: auto_accept
#0 …/app/Http/Controllers/Admin/UsersController.php(378): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined index...', '…/a...', 378, Array)
#1 [internal function]: Fisharebest\Webtrees\Http\Controllers\Admin\UsersController->update(Object(Fisharebest\Webtrees\Http\Request), Object(Fisharebest\Webtrees\User))
#2 …/app/Application.php(45): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\Admin\UsersController), Object(Fisharebest\Webtrees\Http\Request), Object(Fisharebest\Webtrees\User))
#3 …/app/Http/Middleware/RequestRouter.php(68): Fisharebest\Webtrees\Application->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\Admin\UsersController), 'update')
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestRouter->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#5 …/app/Http/Middleware/ModuleMiddleware.php(75): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ModuleMiddleware->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#7 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#9 …/app/Http/Middleware/UseTransaction.php(44): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#11 …/app/Http/Middleware/CheckCsrf.php(63): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#13 …/app/Http/Middleware/DoHousekeeping.php(76): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#15 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#17 …/app/Http/Middleware/UseLocale.php(51): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLocale->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#19 …/app/Http/Middleware/UseTree.php(58): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTree->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#21 …/app/Http/Middleware/UseSession.php(58): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#23 …/app/Http/Middleware/UseFilesystem.php(49): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#25 …/app/Http/Middleware/UseCache.php(44): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#27 …/app/Http/Middleware/UpdateDatabaseSchema.php(56): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Fisharebest\Webtrees\Http\Request), Object(Middleland\Dispatcher))
#29 …/app/Http/Middleware/UseDebugbar.php(64): Middleland\Dispatcher->handle(Object(Fisharebest\Webtrees\Http\Request))
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->proces

**Comment by makitso** [comment]
Sorry, update error.

**Comment by makitso** [comment]
Sorry, still a problem with current github
