### ISSUE TITLE
2.0.0 Beta 3 - mySQL-database error on setup

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#2537]
I tried to setup webtrees 2.0.0 Beta 3 on a test-server. mySQL Database was an empty db - just created. It's a shared hosting with PHP 7.3 and dedicated mySQL server (not on localhost). I got this error:

`SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'betawt_user_gedcom_setting_user_id_gedcom_id_setting_name_primary' is too long (SQL: alter table `betawt_user_gedcom_setting` add primary key `betawt_user_gedcom_setting_user_id_gedcom_id_setting_name_primary`(`user_id`, `gedcom_id`, `setting_name`))`

and:

```
#0 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('alter table `be...', Array, Object(Closure))
#1 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('alter table `be...', Array, Object(Closure))
#2 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/illuminate/database/Schema/Blueprint.php(97): Illuminate\Database\Connection->statement('alter table `be...')
#3 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/illuminate/database/Schema/Builder.php(278): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/illuminate/database/Schema/Builder.php(167): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/app/Schema/Migration0.php(93): Illuminate\Database\Schema\Builder->create('user_gedcom_set...', Object(Closure))
#6 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/app/Services/MigrationService.php(60): Fisharebest\Webtrees\Schema\Migration0->upgrade()
#7 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/app/Http/Controllers/SetupController.php(378): Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 43)
#8 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/app/Http/Controllers/SetupController.php(339): Fisharebest\Webtrees\Http\Controllers\SetupController->createConfigFile(Array)
#9 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/app/Http/Controllers/SetupController.php(152): Fisharebest\Webtrees\Http\Controllers\SetupController->step6Install(Array)
#10 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/app/Http/Middleware/ReadConfigIni.php(66): Fisharebest\Webtrees\Http\Controllers\SetupController->setup(Object(Nyholm\Psr7\ServerRequest))
#11 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#12 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/app/Http/Middleware/HandleExceptions.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#13 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#14 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/app/Http/Middleware/EmitResponse.php(52): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#15 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#16 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/app/Http/Middleware/PhpEnvironment.php(46): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#17 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#19 /var/www/vhosts/hosting128317.a2f12.netcup.net/test.weiland-genealogie.de/webtrees-beta/index.php(40): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#20 {main}
```

**Comment by HonkXL** [comment]
I found the reason: I enteres betawt_ as prefix. With wt_ as prefix is works.
Maybe the field for the table prefix allows to long strings?

**Comment by fisharebest** [comment]
A few years ago, I raised the issue of long index names with the library maintainers - https://github.com/laravel/framework/issues/7889

The workaround is to explicitly specify (short) index names instead of using the automatically generated index names.

**Comment by fisharebest** [comment]
Prefixes up to 15 characters should now be acceptable.
