### ISSUE TITLE
Class 'League\CommonMark\Extension\MiscExtension' not found

### ISSUE THREAD

**Issue by samiona2** [fisharebest/webtrees#2565]
After a second request to update to 2.0 b4 (I had already upgraded, but assumed that something had changed), I encounter the following error on every individual page.
```
Class 'League\CommonMark\Extension\MiscExtension' not found …/vendor/league/commonmark/src/Environment.php:541
#0 …/vendor/league/commonmark/src/Environment.php(191): League\CommonMark\Environment->getMiscExtension()
#1 …/app/Filter.php(94): League\CommonMark\Environment->addBlockRenderer('League\\CommonMa...', Object(League\CommonMark\Block\Renderer\DocumentRenderer))
#2 …/app/Functions/FunctionsPrintFacts.php(868): Fisharebest\Webtrees\Filter::expandUrls('page 3', Object(Fisharebest\Webtrees\Tree))
#3 …/app/Functions/FunctionsPrintFacts.php(618): Fisharebest\Webtrees\Functions\FunctionsPrintFacts::printSourceStructure(Object(Fisharebest\Webtrees\Tree), Array)
#4 …/app/Functions/FunctionsPrintFacts.php(472): Fisharebest\Webtrees\Functions\FunctionsPrintFacts::printFactSources(Object(Fisharebest\Webtrees\Tree), '1 OCCU Rosh Yes...', 2)
#5 …/resources/views/modules/personal_facts/tab.phtml(25): Fisharebest\Webtrees\Functions\FunctionsPrintFacts::printFact(Object(Fisharebest\Webtrees\Fact), Object(Fisharebest\Webtrees\Individual))
#6 …/app/View.php(190): include('/var/www/httpdo...')
#7 …/app/View.php(284): Fisharebest\Webtrees\View->render()
#8 …/app/Helpers/functions.php(178): Fisharebest\Webtrees\View::make('modules/persona...', Array)
#9 …/app/Module/IndividualFactsTabModule.php(158): view('modules/persona...', Array)
#10 …/resources/views/individual-page.phtml(110): Fisharebest\Webtrees\Module\IndividualFactsTabModule->getTabContent(Object(Fisharebest\Webtrees\Individual))
#11 …/app/View.php(190): include('/var/www/httpdo...')
#12 …/app/View.php(284): Fisharebest\Webtrees\View->render()
#13 …/app/Helpers/functions.php(178): Fisharebest\Webtrees\View::make('individual-page', Array)
#14 …/app/Http/ViewResponseTrait.php(46): view('individual-page', Array)
#15 …/app/Http/Controllers/IndividualController.php(147): Fisharebest\Webtrees\Http\Controllers\AbstractBaseController->viewResponse('individual-page', Array)
#16 [internal function]: Fisharebest\Webtrees\Http\Controllers\IndividualController->show(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree), Object(Fisharebest\Webtrees\Services\ClipboardService))
#17 …/app/Application.php(45): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\IndividualController), Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree), Object(Fisharebest\Webtrees\Services\ClipboardService))
#18 …/app/Http/Middleware/RequestRouter.php(73): Fisharebest\Webtrees\Application->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\IndividualController), 'show')
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestRouter->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 …/app/Http/Middleware/ModuleMiddleware.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ModuleMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 …/app/Http/Middleware/UseTransaction.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#26 …/app/Http/Middleware/CheckCsrf.php(63): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 …/app/Http/Middleware/DoHousekeeping.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 …/app/Http/Middleware/CheckForMaintenanceMode.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#34 …/app/Http/Middleware/UseLocale.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLocale->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#36 …/app/Http/Middleware/UseTree.php(59): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTree->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#38 …/app/Http/Middleware/UseSession.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#40 …/app/Http/Middleware/UseFilesystem.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#42 …/app/Http/Middleware/UseCache.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#44 …/app/Http/Middleware/UpdateDatabaseSchema.php(56): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#46 …/app/Http/Middleware/UseDebugbar.php(64): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#48 …/app/Http/Middleware/UseDatabase.php(85): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#50 …/app/Http/Middleware/ReadConfigIni.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#52 …/app/Http/Middleware/HandleExceptions.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#54 …/app/Http/Middleware/EmitResponse.php(52): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#56 …/app/Http/Middleware/PhpEnvironment.php(46): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#59 …/index.php(40): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#60 {main}
```

**Comment by fisharebest** [comment]
You have some files from beta.3

There is a bug (#2558) in beta.3 and beta.4 that prevents the new files being installed.

You should manually install the files for beta.4

**Comment by KosherJava** [comment]
I started with a fresh copy of the entire directory from an unzipped b4, and I only copied over the data folder from the old instance, but no luck. I encounter the same error.
Any ideas?

**Comment by KosherJava** [comment]
The error is ever so slightly different

```
Class 'League\CommonMark\Extension\MiscExtension' not found …/vendor/league/commonmark/src/Environment.php:541
#0 …/vendor/league/commonmark/src/Environment.php(191): League\CommonMark\Environment->getMiscExtension()
#1 …/app/Filter.php(94): League\CommonMark\Environment->addBlockRenderer('League\\CommonMa...', Object(League\CommonMark\Block\Renderer\DocumentRenderer))
#2 …/app/Functions/FunctionsPrintFacts.php(868): Fisharebest\Webtrees\Filter::expandUrls('page 3', Object(Fisharebest\Webtrees\Tree))
#3 …/app/Functions/FunctionsPrintFacts.php(618): Fisharebest\Webtrees\Functions\FunctionsPrintFacts::printSourceStructure(Object(Fisharebest\Webtrees\Tree), Array)
#4 …/app/Functions/FunctionsPrintFacts.php(472): Fisharebest\Webtrees\Functions\FunctionsPrintFacts::printFactSources(Object(Fisharebest\Webtrees\Tree), '1 OCCU Rosh Yes...', 2)
#5 …/resources/views/modules/personal_facts/tab.phtml(25): Fisharebest\Webtrees\Functions\FunctionsPrintFacts::printFact(Object(Fisharebest\Webtrees\Fact), Object(Fisharebest\Webtrees\Individual))
#6 …/app/View.php(190): include('/var/www/httpdo...')
#7 …/app/View.php(284): Fisharebest\Webtrees\View->render()
#8 …/app/Helpers/functions.php(178): Fisharebest\Webtrees\View::make('modules/persona...', Array)
#9 …/app/Module/IndividualFactsTabModule.php(158): view('modules/persona...', Array)
#10 …/resources/views/individual-page.phtml(110): Fisharebest\Webtrees\Module\IndividualFactsTabModule->getTabContent(Object(Fisharebest\Webtrees\Individual))
#11 …/app/View.php(190): include('/var/www/httpdo...')
#12 …/app/View.php(284): Fisharebest\Webtrees\View->render()
#13 …/app/Helpers/functions.php(178): Fisharebest\Webtrees\View::make('individual-page', Array)
#14 …/app/Http/ViewResponseTrait.php(46): view('individual-page', Array)
#15 …/app/Http/Controllers/IndividualController.php(147): Fisharebest\Webtrees\Http\Controllers\AbstractBaseController->viewResponse('individual-page', Array)
#16 [internal function]: Fisharebest\Webtrees\Http\Controllers\IndividualController->show(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree), Object(Fisharebest\Webtrees\Services\ClipboardService))
#17 …/app/Application.php(45): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\IndividualController), Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree), Object(Fisharebest\Webtrees\Services\ClipboardService))
#18 …/app/Http/Middleware/RequestRouter.php(73): Fisharebest\Webtrees\Application->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\IndividualController), 'show')
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestRouter->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 …/app/Http/Middleware/ModuleMiddleware.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ModuleMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 …/app/Http/Middleware/UseTransaction.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#26 …/app/Http/Middleware/CheckCsrf.php(63): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 …/app/Http/Middleware/DoHousekeeping.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 …/app/Http/Middleware/CheckForMaintenanceMode.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#34 …/app/Http/Middleware/UseLocale.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLocale->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#36 …/app/Http/Middleware/UseTree.php(59): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTree->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#38 …/app/Http/Middleware/UseSession.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#40 …/app/Http/Middleware/UseFilesystem.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#42 …/app/Http/Middleware/UseCache.php(44): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#44 …/app/Http/Middleware/UpdateDatabaseSchema.php(56): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#46 …/app/Http/Middleware/UseDebugbar.php(64): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#48 …/app/Http/Middleware/UseDatabase.php(85): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#50 …/app/Http/Middleware/ReadConfigIni.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#52 …/app/Http/Middleware/HandleExceptions.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#54 …/app/Http/Middleware/EmitResponse.php(52): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#56 …/app/Http/Middleware/PhpEnvironment.php(46): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#59 …/index.php(40): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#60 {main}
```

**Comment by fisharebest** [comment]
In beta.3, line 541 agrees with your error message:
https://github.com/fisharebest/webtrees/blob/2.0.0-beta.3/vendor/league/commonmark/src/Environment.php

In beta.4, the file does not even have 541 lines.
https://github.com/fisharebest/webtrees/blob/2.0.0-beta.4/vendor/league/commonmark/src/Environment.php

Your error looks very much like you have the beta.3 version of this file.

**Comment by samiona2** [comment]
Thanks @fisharebest . Manual install addressed the issues. Thanks
