### ISSUE TITLE
2.0-b4: Password Change Throws Errors

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#2569]

**Comment by dbq-andersons** [comment]
Running the currently published 2.0.0-beta.4

Changed my password today and the site wasn't happy until I commented out all references to the theme in AccountController.php since changing the them doesn't appear to be an option on the "My Account" dialog anymore (which is fine by me). Apparently, the code in AccountController is still expecting it.  Here's the error header (I truncated the rest):

`Undefined index: theme …/app/Http/Controllers/AccountController.php:111
#0 …/app/Http/Controllers/AccountController.php(111): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined index...', '/tools/webdocs/...', 111, Array)
#1 [internal function]: Fisharebest\Webtrees\Http\Controllers\AccountController->update(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree), Object(Fisharebest\Webtrees\User))
#2 …/app/Application.php(45): ReflectionMethod->invoke(Object(Fisharebest\Webtrees\Http\Controllers\AccountController), Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Tree), Object(Fisharebest\Webtrees\User))
#3 …/app/Http/Middleware/RequestRouter.php(68): Fisharebest\Webtrees\Application->dispatch(Object(Fisharebest\Webtrees\Http\Controllers\AccountController), 'update')
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestRouter->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#5 …/app/Module/HitCountFooterModule.php(141): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))`

I commented out lines 111,143 and 150 and then everything worked fine.

Cheers,

Bill Anderson

**Comment by fisharebest** [comment]
> changing the theme doesn't appear to be an option on the "My Account" dialog anymore

What makes you say this?

I see the option in both the user-account page and the admin-edit-user page...

**Comment by dbq-andersons** [comment]
OK.  I'm sorely confused now.

I'm logged into my site as the site administrator (the only login on my site) and I've attached the page I see when I go to the "My Account" link off the "My Pages" drop-down (http://genealogy.dbq-andersons.com/index.php?route=my-account).

![my-account-page](https://user-images.githubusercontent.com/43183321/64529819-59512a00-d2d1-11e9-9a5c-caf2b2a440e4.jpg)

If I go to the same page when logged into the demo site as the any of the three users listed (member, editor, or moderator), I get a page with two more options: the theme drop-down and the "Delete your account" button.  Makes sense that the "Delete your account button" is hidden from my account on my site since it's a site admin and the only account on the server.  Perhaps the same mechanism that hides that button is hiding the Theme drop-down as well?  I'll poke around...

Thanks,
Bill

**Comment by fisharebest** [comment]
OK - I see it.

The "theme" option is supressed when you only have one theme.

Do we even need this option?   Probably not.  Users can change their theme/language using the links in the header.

**Comment by dbq-andersons** [comment]
I just tested it and sure enough, if I enable a second theme, the drop-down appears and the page works fine when I hit "Save." Re-disable that second theme and the page bombs when I hit "Save." Thanks for the digging.

I agree with you that it might not even be needed given the other places to change the theme.

Or, I could give up a little control and enable more than one theme. :-)
