### ISSUE TITLE
Git - Interactive tree - click on individual results in error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2678]
Seems to be two errors produced, one in console
```
Argument 1 passed to Fisharebest\Webtrees\Module\InteractiveTree\TreeView::getPersons() must be an instance of Fisharebest\Webtrees\Tree, null given, called in …\app\Module\InteractiveTreeModule.php on line 253 …\app\Module\InteractiveTree\TreeView.php:77
#0 …\app\Module\InteractiveTreeModule.php(253): Fisharebest\Webtrees\Module\InteractiveTree\TreeView->getPersons(NULL, 'pF133@t;pF214@b...')
#1 …\app\Http\RequestHandlers\ModuleAction.php(93): Fisharebest\Webtrees\Module\InteractiveTreeModule->getPersonsAction(Object(Nyholm\Psr7\ServerRequest))
#2 …\app\Http\Middleware\WrapHandler.php(76): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle(Object(Nyholm\Psr7\ServerRequest))
etc.
```
and 2nd on screen
![demo](https://user-images.githubusercontent.com/104515/67293874-f4e2d680-f4dc-11e9-9406-5b06c2a1956e.jpg)

**Comment by ddrury** [comment]
Url that produces the console error is `http://webtrees-2.0.home.lan/index.php?route=/module/tree/Details&pid=I270&ged=drury&instance=tvTab`

**Comment by ddrury** [comment]
The following fixes things but I suspect I'm getting the tree instance incorrectly
In InteractiveTreeModule::getDetailsAction() (line 221)
repace the first few lines with

```
        $tree_name  = $request->getQueryParams()['ged'];
        $pid        = $request->getQueryParams()['pid'];

        $tree = Tree::findByName($tree_name);
```
