### ISSUE TITLE
Custom statistic charts broken

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2680]
https://dev.webtrees.net/demo-dev/module/statistics_chart/Chart/demo#tab-tab-bcc78d5e673630ad67f4f6f15f90a4f6
```

Unresolvable dependency resolving [Parameter #0 [  integer $id ]] in class Fisharebest\Webtrees\Tree …/vendor/illuminate/container/Container.php:975
#0 …/vendor/illuminate/container/Container.php(913): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter))
#1 …/vendor/illuminate/container/Container.php(854): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#2 …/vendor/illuminate/container/Container.php(816): Illuminate\Container\Container->resolveDependencies(Array)
#3 …/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('Fisharebest\\Web...')
#4 …/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('Fisharebest\\Web...', Array)
#5 …/vendor/illuminate/container/Container.php(927): Illuminate\Container\Container->make('Fisharebest\\Web...')
#6 …/vendor/illuminate/container/Container.php(855): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#7 …/vendor/illuminate/container/Container.php(816): Illuminate\Container\Container->resolveDependencies(Array)
#8 …/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('Fisharebest\\Web...')
#9 …/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('Fisharebest\\Web...', Array)
#10 …/app/Helpers/functions.php(45): Illuminate\Container\Container->make('Fisharebest\\Web...')
```

**Comment by magicsunday** [comment]
The problem is that the tree is not initialized after a GET request. If I change this to POST in the form and the jquery call. I also need to add the following after app/Http/Middleware/Router.php line 89 as the tree attribute is still missing in the route.

```
        // Add tree attribute from POST data to route if missing
        if ($route && $route->attributes && !$route->attributes['tree'] && $request->getParsedBody()['tree']) {
            $route->attributes(['tree' => $request->getParsedBody()['tree']]);
        }

```
