### ISSUE TITLE
test site - user blog - tree is missing - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2714]
Undefined variable: tree …/resources/views/modules/user_blog/list.phtml:26
#0 …/resources/views/modules/user_blog/list.phtml(26): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined varia...', '/home/amitys/te...', 26, Array)
#1 …/app/View.php(186): include('/home/amitys/te...')
#2 …/app/View.php(282): Fisharebest\Webtrees\View->render()
etc.

**Comment by melizaa** [comment]
In test and future

I saw the error also in the stories and in the message page. I cannot be sure until I can again enter my test sites.
