### ISSUE TITLE
Github - individual page - Media and Album tabs

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2740]
Clicking on the image title (not the image itself) results in
```
Undefined variable: data_filesystem …\resources\views\media-page.phtml:115
#0 …\resources\views\media-page.phtml(115): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined varia...', 'D:\\Server\\nginx...', 115, Array)
#1 …\app\View.php(186): include('D:\\Server\\nginx...')
#2 …\app\View.php(282): Fisharebest\Webtrees\View->render()
#3 …\app\Helpers\functions.php(217): Fisharebest\Webtrees\View::make('media-page', Array)
#4 …\app\Http\ViewResponseTrait.php(51): view('media-page', Array)
#5 …\app\Http\RequestHandlers\MediaPage.php(88): Fisharebest\Webtrees\Http\RequestHandlers\MediaPage->viewResponse('media-page', Array)
#6 …\app\Http\Middleware\WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\MediaPage->handle(Object(Nyholm\Psr7\ServerRequest))
#7 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#8 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#9 …\app\Http\Middleware\Router.php(122): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#10 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 …\app\Http\Middleware\BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#12 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 …\app\Http\Middleware\LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 …\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 …\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#17 …\app\Http\Middleware\UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3)
#18 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#19 …\app\Http\Middleware\CheckCsrf.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#20 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#21 …\app\Http\Middleware\DoHousekeeping.php(83): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
etc..
```

**Comment by fisharebest** [comment]
I am getting rid of global variables (and things that behave like globals, such as static data, etc.).

Responses should depend on requests (and only requests - not on global information.

The filesystem used to be part of the global state.  Now, it is passed in with the request.
