### ISSUE TITLE
Github - Tree Selection in Control Panel Errors Out

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#2744]
Hi Everyone,

On the latest GitHub pull, when I select a tree from the Family Trees section of the control panel, I get the following errors:
```
Links are not supported, encountered link at data/sanitized-tree_wt.ged …/vendor/league/flysystem/src/NotSupportedException.php:21
#0 …/vendor/league/flysystem/src/Adapter/Local.php(451): League\Flysystem\NotSupportedException::forLink(Object(DirectoryIterator))
#1 …/vendor/league/flysystem/src/Adapter/Local.php(287): League\Flysystem\Adapter\Local->normalizeFileInfo(Object(DirectoryIterator))
#2 …/vendor/league/flysystem-cached-adapter/src/CachedAdapter.php(249): League\Flysystem\Adapter\Local->listContents('', false)
#3 …/vendor/league/flysystem/src/Filesystem.php(271): League\Flysystem\Cached\CachedAdapter->listContents('', false)
#4 …/app/Http/Controllers/AdminTreesController.php(1768): League\Flysystem\Filesystem->listContents()
#5 …/app/Http/Controllers/AdminTreesController.php(438): Fisharebest\Webtrees\Http\Controllers\AdminTreesController->gedcomFiles(Object(League\Flysystem\Filesystem))
#6 …/app/Http/Middleware/WrapHandler.php(79): Fisharebest\Webtrees\Http\Controllers\AdminTreesController->index(Object(Nyholm\Psr7\ServerRequest))
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#8 …/app/Module/HitCountFooterModule.php(147): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#10 …/app/Http/Middleware/AuthManager.php(60): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
```
I can provide lines 11-60 if needed.

I cleared my cache and can replicate on both Firefox and Chrome.

Thanks,

Bill

**Comment by fisharebest** [comment]
> Links are not supported, encountered link at data/sanitized-tree_wt.ged

You have used a symbolic link somewhere in either your "data" folder, or one of your "media" folders.

As the error message says, these are not supported.
Also, a media folder cannot use '../' to access a parent folder outside the data folder.

The reason is that we now access the data folder via an abstraction layer [flysystem](https://flysystem.thephpleague.com/docs/).

This abstraction layer will let us use a range of different/remote filesystems (e.g. DropBox, GoogleDrive, AWS-S3, SFTP, etc.) for storing our data.

It also provides protection against any coding error that might otherwise allow access to any parent folders.

So, I'm afraid you'll have to reconfigure your setup.

**Comment by dbq-andersons** [comment]
That makes sense now that I know what's going on.  I pulled the two sym-links I had in data/ and things look much better now.

Cheers,

Bill
