### ISSUE TITLE
Github-Control panel-manage media

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2751]
With local files selected and filtered to display a pdf file; clicking on the media image (icon in this instance) produces the following error message
```
Too few arguments to function Fisharebest\Webtrees\Tree::mediaFilesystem(), 0 passed in …\app\Http\Controllers\MediaFileController.php on line 101 and exactly 1 expected …\app\Tree.php:734
#0 …\app\Http\Controllers\MediaFileController.php(101): Fisharebest\Webtrees\Tree->mediaFilesystem()
#1 …\app\Http\Middleware\WrapHandler.php(79): Fisharebest\Webtrees\Http\Controllers\MediaFileController->mediaDownload(Object(Nyholm\Psr7\ServerRequest))
#2 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#3 …\app\Module\HitCountFooterModule.php(147): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#4 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#5 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#6 …\app\Http\Middleware\Router.php(122): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#7 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#8 …\app\Http\Middleware\BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#9 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#10 …\app\Http\Middleware\LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#11 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#12 …\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
etc.
```

**Comment by ddrury** [comment]
Actually seems to be any non-image media oblect
