### ISSUE TITLE
Github - Shared note edit

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2764]
produces following error

```
assert(): assert($tree instanceof Tree) failed …\app\Http\Middleware\AuthEditor.php:51
#0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'assert(): asser...', 'D:\\Server\\nginx...', 51, Array)
#1 …\app\Http\Middleware\AuthEditor.php(51): assert(false, 'assert($tree in...')
#2 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthEditor->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#3 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#4 …\app\Http\Middleware\Router.php(122): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#5 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#6 …\app\Http\Middleware\BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#7 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#8 …\app\Http\Middleware\LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#9 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#10 …\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#11 …\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#12 …\app\Http\Middleware\UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3)
#13 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#14 …\app\Http\Middleware\CheckCsrf.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#15 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#16 …\app\Http\Middleware\DoHousekeeping.php(83): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#17 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 …\app\Http\Middleware\UseTheme.php(72): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#19 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 …\app\Http\Middleware\CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#21 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …\app\Http\Middleware\UseLocale.php(53): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#23 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLocale->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 …\app\Http\Middleware\UseSession.php(63): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#25 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#26 …\app\Http\Middleware\UseFilesystem.php(60): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#27 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 …\app\Http\Middleware\UseCache.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#29 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 …\app\Http\Middleware\UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#31 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 …\app\Http\Middleware\UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(
etc.
```

**Comment by fisharebest** [comment]
How did you trigger this?

Did you follow an expired link.  e.g. you'd logged out in another tab (or timed-out through inactivity), and then clicked a link that was already on the page?

**Comment by fisharebest** [comment]
My guess is that an expired link is being treated as an invalid link.

**Comment by ddrury** [comment]
Lists - Shared notes - Pick one - Edit - Save
