### ISSUE TITLE
2.0.1-Place Import Fails with Undefined Index

### ISSUE THREAD

**Issue by dbq-andersons** [fisharebest/webtrees#2927]
I'm pretty sure this is an issue and not a self-induced error, but I could be (and often am) wrong.

When I click on the "Import file" button at the bottom of http://genealogy.dbq-andersons.com/admin/map-data, it throws this error.  I know this worked on earlier betas of 2.0.0, but it has been a while since I've run an import. (2.0.0-b3 maybe??).  

```
Undefined index: extension …/app/Http/Controllers/Admin/LocationController.php:619
#0 …/app/Http/Controllers/Admin/LocationController.php(619): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined index...', '/tools/webdocs/...', 619, Array)
#1 [internal function]: Fisharebest\Webtrees\Http\Controllers\Admin\LocationController::Fisharebest\Webtrees\Http\Controllers\Admin\{closure}(Array, 3)
#2 …/vendor/illuminate/support/Arr.php(611): array_filter(Array, Object(Closure), 1)
#3 …/vendor/illuminate/support/Collection.php(549): Illuminate\Support\Arr::where(Array, Object(Closure))
#4 …/app/Http/Controllers/Admin/LocationController.php(620): Illuminate\Support\Collection->filter(Object(Closure))
#5 …/app/Http/Middleware/WrapHandler.php(79): Fisharebest\Webtrees\Http\Controllers\Admin\LocationController->importLocations(Object(Nyholm\Psr7\ServerRequest))
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#7 …/app/Http/Middleware/AuthAdministrator.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthAdministrator->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#9 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#12 …/app/Http/Middleware/Router.php(121): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#14 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
```

Cheers,

Bill Anderson

**Comment by fisharebest** [comment]
OK - this is caused by a file without an extension.  e.g. `foo` instead of `foo.txt`.

Should be easy to fix.

**Comment by dbq-andersons** [comment]
I gotta give ya some easy ones.  FYI, all of the files in data/places have a .csv extension.  Everything looks fine now.

Cheers,

Bill
