### ISSUE TITLE
Email settings error after upgrade from 1.7.9

### ISSUE THREAD

**Issue by singalen** [fisharebest/webtrees#2943]
Got this stack on email settgins page:

```substr() expects parameter 1 to be string, bool given …/app/Services/EmailService.php:199
#0 …/app/Services/EmailService.php(199): substr(false, 1)
#1 …/app/Http/RequestHandlers/EmailPreferencesPage.php(78): Fisharebest\Webtrees\Services\EmailService->isValidEmail('tree.victorserg...')
#2 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\EmailPreferencesPage->handle(Object(Nyholm\Psr7\ServerRequest))
```

`SMTP_FROM_NAME` was just the domain name. The error went away when I set it to a valid email address.

**Comment by fisharebest** [comment]
This was actually fixed earlier today;

https://github.com/fisharebest/webtrees/commit/ff00880fa46e750a1a93bca15cee266167a0e2ad
