### ISSUE TITLE
V2 Welcome page error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3035]
This is as a result of installing the latest master with a v1.7 database (which is now at schema 43)
The installed blocks which trigger this error are statistics, on this day and slideshow. `app\Http\RequestHandlers\TreePageBlock.php/` does exist

This is on a new server setup (nginx/php-fpm7.4) using your suggested nginx config for pretty urls
```
Class Fisharebest\Webtrees\Http\RequestHandlers\TreePageBlock does not exist …/vendor/illuminate/container/Container.php:788
#0 …/vendor/illuminate/container/Container.php(788): ReflectionClass->__construct()
#1 …/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build()
#2 …/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve()
#3 …/app/Helpers/functions.php(45): Illuminate\Container\Container->make()
#4 …/app/Http/Middleware/WrapHandler.php(83): app()
#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#6 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#8 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#11 …/app/Http/Middleware/Router.php(134): Middleland\Dispatcher->dispatch()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#13 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#15 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#17 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#18 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#19 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#21 …/app/Http/Middleware/DoHousekeeping.php(81): Middleland\Dispatcher->handle()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#23 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#25 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#27 …/app/Http/Middleware/UseLanguage.php(73): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#29 …/app/Http/Middleware/UseSession.php(73): Middleland\Dispatcher->handle()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#31 …/app/Http/Middleware/UseFilesystem.php(58): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process()
#33 …/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process()
#35 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#37 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process()
#39 …/app/Http/Middleware/UseDatabase.php(95): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#41 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle()
#42 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#44 …/app/Http/Middleware/HandleExceptions.php(76): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#46 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#48 …/app/Http/Middleware/ReadConfigIni.php(65): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#50 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#52 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#54 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#57 …/index.php(55): Middleland\Dispatcher->dispatch()
#58 {main}
```

**Comment by ddrury** [comment]
Hang fire for a bit it may be a server problem. On the website home page I get the error as above logged in or not but on my homepage for the same modules I get a server 500 error. Any advice welcome!

**Comment by fisharebest** [comment]
> Class Fisharebest\Webtrees\Http\RequestHandlers\TreePageBlock does not exist

The usual cause of this error is that the file `app/Http/RequestHandlers/TreePageBlock.php`
does not exist or is corrupt.

Alternatively, the autoloader is failing `vendor/autoload.php` and `vendor/composer/autoload*`

**Comment by ddrury** [comment]
fixed it (hopefully for good!). I discovered that php-fpm.conf was over-riding the php error reporting. Setting that to display errors meant I then got a php error instead of the server 500 error. The error indicated a composer autoload problem (as you suggested)  so I installed composer - don't see why that was necessary but as I say it's working now

**Comment by ddrury** [comment]
Oh spoke too soon - the error as above is back!!

**Comment by ddrury** [comment]
php-fpm had stopped!!
