### ISSUE TITLE
Error in Changes Report - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3157]
I add a spouse and do not approve the changes. I create a changes report and I see errors.

Call to a member function facts() on null …/app/Report/ReportParserGenerate.php:1342
#0 …/app/Report/ReportParserGenerate.php(245): Fisharebest\Webtrees\Report\ReportParserGenerate->factsStartHandler(Array)
#1 …/app/Report/ReportParserGenerate.php(2329): Fisharebest\Webtrees\Report\ReportParserGenerate->startElement(Resource id #538, 'Facts', Array)
#2 [internal function]: Fisharebest\Webtrees\Report\ReportParserGenerate->Fisharebest\Webtrees\Report\{closure}(Resource id #538, 'Facts', Array)
#3 …/app/Report/ReportParserGenerate.php(2343): xml_parse(Resource id #538, '<tempdoc>\n\t\t\t\t\t...', true)
etc.

In my pre wt 2.0.0 production system I get
/home/amitys/www.amitys.com/webtrees/app/Report/ReportParserGenerate.php:1198 Call to a member function getFacts() on null #0 /app/Report/ReportParserGenerate.php:157 Error("Call to a member function getFacts() on null") #1 unknown:unknown startElement([resource], 'Facts', [array]) #2 /app/Report/ReportParserGenerate.php:2267 xml_parse([resource], '

**Comment by melizaa** [comment]
I changed locally the file in the production system. I do no longer see the error.

Thank you!
