### ISSUE TITLE
Error for Hebrew date without year - 2.0.7-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3399]
I have today updated the test test system code - 6f689161039..20b78d81a8e  master     -> origin/master
I have not yet updated the future test code.

Undefined offset: -3 …/vendor/fisharebest/ext-calendar/src/JewishCalendar.php:343
#0 …/vendor/fisharebest/ext-calendar/src/JewishCalendar.php(343): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined offse...', '/home/amitys/te...', 343, Array)
etc.

**Comment by melizaa** [comment]
The error is in some other block.
Greg, I see the error using your user at least on the home page.
Have to run!

**Comment by melizaa** [comment]
I see the error
Undefined offset: -3 …/vendor/fisharebest/ext-calendar/src/JewishCalendar.php:343
#0 …/vendor/fisharebest/ext-calendar/src/JewishCalendar.php(343): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined offse...', '/home/amitys/fu...', 343, Array)
etc.
in the future test system.

**Comment by melizaa** [comment]
I see the error in the Yahrzeiten (10 days), in Upcoming Events (including dead), in On this day calendar on 10 July 2020 or 18 Tamuz 5780 and In this month... July 2020.

The cause is a death record with the Hebrew death date 18 Tamuz without a year.

webtrees pre 2.0.0 handles this date correctly.

I do see a death date 9 July without a year in On this day in wt 2.0.7 - dev. 

When I try to define death dates 15 Tamuz or 7 July, without a year, I get also the error.

**Comment by melizaa** [comment]
If I know the Hebrew death day and month, I fill them to my site, because they define the person's Yahrzeiten.
