### ISSUE TITLE
Can't go to controlpanel after update from 2.06 to 2.07

### ISSUE THREAD

**Issue by Lars1963** [fisharebest/webtrees#3440]
Controlpanel can't be opened with this error after update. I did have to delete offline.txt manually as well.

```
map-data …/vendor/aura/router/src/Map.php:152
#0 …/app/Helpers/functions.php(169): Aura\Router\Map->getRoute()
#1 …/resources/views/admin/control-panel.phtml(657): route()
#2 …/app/View.php(186): include('/var/www/webtre...')
#3 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#4 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make()
#5 …/app/Http/ViewResponseTrait.php(51): view()
#6 …/app/Http/RequestHandlers/ControlPanel.php(192): Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel->viewResponse()
#7 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#9 …/app/Http/Middleware/AuthAdministrator.php(52): Middleland\Dispatcher->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthAdministrator->process()
#11 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#14 …/app/Http/Middleware/Router.php(134): Middleland\Dispatcher->dispatch()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#16 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#18 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#20 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#21 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#22 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#24 …/app/Http/Middleware/DoHousekeeping.php(81): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#26 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#28 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#30 …/app/Http/Middleware/RegisterFactories.php(73): Middleland\Dispatcher->handle()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process()
#32 …/app/Http/Middleware/UseLanguage.php(73): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#34 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#36 …/app/Http/Middleware/UseFilesystem.php(58): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process()
#38 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#40 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process()
#42 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#44 …/app/Http/Middleware/BadBotBlocker.php(213): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#46 …/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process()
#48 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle()
#49 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#51 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#53 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#55 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#57 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#59 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#61 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle()
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process()
#63 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#64 …/index.php(57): Middleland\Dispatcher->dispatch()
#65 {main}
```

**Comment by Lars1963** [comment]
I solved by completely re-installing webtrees .
