### ISSUE TITLE
Ran auto-update to 2.0.10 - site diplays error

### ISSUE THREAD

**Issue by ngraziani** [fisharebest/webtrees#3573]
Just ran the update from the link in the page header for the "New Release - Update Now".  Says it completed successfully, but when going to the site..... Thoughts?

---------------------------------------------------
Illuminate\Container\EntryNotFoundException: Fisharebest\Webtrees\Http\Middleware\UseCache in /opt/bitnami/apache/htdocs/family/vendor/illuminate/container/Container.php:630 Stack trace: #0 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(97): Illuminate\Container\Container->get() #1 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(126): Middleland\Dispatcher->get() #2 /opt/bitnami/apache/htdocs/family/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle() #3 /opt/bitnami/apache/htdocs/family/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #4 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #5 /opt/bitnami/apache/htdocs/family/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #6 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #7 /opt/bitnami/apache/htdocs/family/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle() #8 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #9 /opt/bitnami/apache/htdocs/family/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle() #10 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #11 /opt/bitnami/apache/htdocs/family/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle() #12 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #13 /opt/bitnami/apache/htdocs/family/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #14 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #15 /opt/bitnami/apache/htdocs/family/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle() #16 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process() #17 /opt/bitnami/apache/htdocs/family/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #18 /opt/bitnami/apache/htdocs/family/index.php(57): Middleland\Dispatcher->dispatch() #19 {main}

**Comment by ngraziani** [comment]
Nope.  Still can't get into the site....
