### ISSUE TITLE
I get Fatal error when I try to import a new copy of a GEDCOM file from the server. It is imported successfully  when I try again to import it.

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3576]
```
Fatal error: Uncaught ErrorException: Trying to get property 'name' of   non-object in   /home/amitys/test.amitys.com/resources/views/layouts/default.phtml:71 Stack   trace:
#0 /home/amitys/test.amitys.com/resources/views/layouts/default.phtml(71):   Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Trying to   get p...', '/home/amitys/te...', 71, Array)
#1 /home/amitys/test.amitys.com/app/View.php(189): include('/home/amitys/te...')
#2 /home/amitys/test.amitys.com/app/View.php(286): Fisharebest\Webtrees\View->render()
#3 /home/amitys/test.amitys.com/app/Helpers/functions.php(203):   Fisharebest\Webtrees\View::make('layouts/default', Array)
#4 /home/amitys/test.amitys.com/app/Http/ViewResponseTrait.php(58):   view('layouts/default', Array)
#5 /home/amitys/test.amitys.com/app/Http/Middleware/HandleExceptions.php(176):   Fisharebest\Webtrees\Http\Middleware\HandleExceptions->viewResponse('components/aler...',   Array, 404)
#6 /home/amitys/test.amitys.com/app/Http/Middleware/HandleExceptions.php(99):   Fisharebest\Webtrees\Http\ in /home/amitys/test.amitys.com/resources/views/layouts/default.phtml on line 71
```

**Comment by melizaa** [comment]
I have received this error twice in both my test systems, the last times for 2.0.11-dev.

**Comment by fisharebest** [comment]
This is an error in the error handler.

It is trying to display an error using the default/genealogy page layout - which requires an associated tree.

However, the error came from the admin pages - which do not have an associated tree.

There have been some improvements to the error handler since then, which should prevent this (and allow you to see the actual/original error)
