### ISSUE TITLE
Error with installation at mysql database

### ISSUE THREAD

**Issue by dtrabuc** [fisharebest/webtrees#3608]
Hi dev from `webtrees!`
I m dylan trabuc from france and i am trying to install your software on my website...
all steps had pass but at a moment just at the last step of name user and password 
there is these errors line...

```
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'footer_order' (SQL: alter table `wt_module` add `footer_order` int null after `sidebar_order`)
#0 /homepages/23/d851119122/htdocs/webtrees/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('alter table `wt...', Array, Object(Closure))
#1 /homepages/23/d851119122/htdocs/webtrees/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('alter table `wt...', Array, Object(Closure))
#2 /homepages/23/d851119122/htdocs/webtrees/vendor/illuminate/database/Schema/Blueprint.php(97): Illuminate\Database\Connection->statement('alter table `wt...')
#3 /homepages/23/d851119122/htdocs/webtrees/vendor/illuminate/database/Schema/Builder.php(278): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 /homepages/23/d851119122/htdocs/webtrees/vendor/illuminate/database/Schema/Builder.php(151): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 /homepages/23/d851119122/htdocs/webtrees/app/Schema/Migration41.php(39): Illuminate\Database\Schema\Builder->table('module', Object(Closure))
#6 /homepages/23/d851119122/htdocs/webtrees/app/Services/MigrationService.php(69): Fisharebest\Webtrees\Schema\Migration41->upgrade()
#7 /homepages/23/d851119122/htdocs/webtrees/app/Http/RequestHandlers/SetupWizard.php(395): Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 44)
#8 /homepages/23/d851119122/htdocs/webtrees/app/Http/RequestHandlers/SetupWizard.php(356): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->createConfigFile(Array)
#9 /homepages/23/d851119122/htdocs/webtrees/app/Http/RequestHandlers/SetupWizard.php(193): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->step6Install(Array)
#10 /homepages/23/d851119122/htdocs/webtrees/app/Http/Middleware/ReadConfigIni.php(69): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->handle(Object(Nyholm\Psr7\ServerRequest))
#11 /homepages/23/d851119122/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard))
#12 /homepages/23/d851119122/htdocs/webtrees/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#13 /homepages/23/d851119122/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#14 /homepages/23/d851119122/htdocs/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#15 /homepages/23/d851119122/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#16 /homepages/23/d851119122/htdocs/webtrees/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#17 /homepages/23/d851119122/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 /homepages/23/d851119122/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#19 /homepages/23/d851119122/htdocs/webtrees/index.php(57): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
```

help me please

thx 
dylan

**Comment by fisharebest** [comment]
Perhaps the installation was interrupted.

Do you have access to your database (e.g. via phpMyAdmin)?

If this is a new installation, delete all the tables (and the file `data/config.ini.php` if it exists), and start again.

If you are upgrading an existing installation, find the table `wt_site_setting`, and the entry for `WT_SCHEMA_VERSION` and update the value from `41` to `42`.

**Comment by fisharebest** [comment]
Any news?  Did you manage to complete the installation?

**Comment by dtrabuc** [comment]
excuse me for the late reply i have not yet retry to launch my webtrees server so no news for the moment

Best regards
D.T

________________________________
De : Greg Roach <notifications@github.com>
Envoyé : vendredi 27 novembre 2020 à 21:33
À : fisharebest/webtrees
Cc : dtrabuc; Manual
Objet : Re: [fisharebest/webtrees] Error with installation at mysql database (#3608)


Perhaps the installation was interrupted.

Do you have access to your database (e.g. via phpMyAdmin)?

If this is a new installation, delete all the tables (and the file data/config.ini.php if it exists), and start again.

If you are upgrading an existing installation, find the table wt_site_setting, and the entry for WT_SCHEMA_VERSION and update the value from 41 to 42.

**Comment by fisharebest** [comment]
If the above steps (or a clean re-installation) do not work, please open a new issue.
