### ISSUE TITLE
An error occurred during user registration

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#3614]
An error occurred during user registration.
Every time a user registers, this error occurs.
In the website log, the same error appears three times at the same point in time.
In the Control Panel, the user has successfully registered.

I use sql query for duplicate records without any result.
`SELECT * FROM `wt_user` WHERE `user_name` in (select `user_name` from `wt_user` group by `user_name` HAVING COUNT(`user_name`) >1)`

Here is the error message:

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;wanghe&#039; for key &#039;wt_user_user_name_unique&#039; (SQL: insert into `wt_user` (`user_name`, `real_name`, `email`, `password`) values (wanghe, Wanghe, aaa@139.cn, $2y$10$.A/.3HH0zb7feaeggPUI80uWhyGJGCJMkrGLGwS.HOorn.dfnc859G)) …/vendor/illuminate/database/Connection.php:664 #0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection-&gt;runQueryCallback() #1 …/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection-&gt;run() #2 …/vendor/illuminate/database/Connection.php(411): Illuminate\Database\Connection-&gt;statement() #3 …/vendor/illuminate/database/Query/Builder.php(2646): Illuminate\Database\Connection-&gt;insert() #4 …/app/Services/UserService.php(343): Illuminate\Database\Query\Builder-&gt;insert() #5 …/app/Http/RequestHandlers/RegisterAction.php(127): Fisharebest\Webtrees\Services\UserService-&gt;create() #6 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\RegisterAction-&gt;handle() #7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler-&gt;process() <b>#8 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher-&gt;handle()</b> #9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule-&gt;process() #10 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle() #11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #13 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher-&gt;dispatch() #14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):`

**Comment by DaPoHou** [comment]
It is caused by multiple clicks during user registration.
It is recommended that all buttons be changed to be clickable only once.
