### ISSUE TITLE
Updating schema to v45 fails on PostgreSQL (Datatype mismatch)

### ISSUE THREAD

**Issue by upaternostro** [fisharebest/webtrees#3693]
Hi,

trying to install on PostgreSQL 9.6 current master leads to:

`SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "latitude" is of type double precision but expression is of type text`
`LINE 1: ...EN 0 THEN NULL ELSE pl_parent_id END, "pl_place", REPLACE(RE...`
`                                                                                                        ^`
`HINT: You will need to rewrite or cast the expression. (SQL: insert into "wt_place_location" ("id", "parent_id",
"place", "latitude", "longitude") select "pl_id", CASE pl_parent_id WHEN 0 THEN NULL ELSE pl_parent_id END,
"pl_place", REPLACE(REPLACE(pl_lati, 'S', '-'), 'N', ''), REPLACE(REPLACE(pl_long, 'W', '-'), 'E', '') from
"wt_placelocation" left join "wt_place_location" on "id" = "pl_id" where "id" is null order by "pl_id" asc)`

on

`#0 /var/www/webtrees.lan.paternostro.priv/data/vendor/illuminate/database/Connection.php(624):
Illuminate\Database\Connection->runQueryCallback('insert into "wt...', Array, Object(Closure))`
`#1 /var/www/webtrees.lan.paternostro.priv/data/vendor/illuminate/database/Connection.php(459):
Illuminate\Database\Connection->run('insert into "wt...', Array, Object(Closure))`
`#2 /var/www/webtrees.lan.paternostro.priv/data/vendor/illuminate/database/Connection.php(411):
Illuminate\Database\Connection->statement('insert into "wt...', Array)`
`#3 /var/www/webtrees.lan.paternostro.priv/data/vendor/illuminate/database/Query/Builder.php(2706):
Illuminate\Database\Connection->insert('insert into "wt...', Array)`
`#4 /var/www/webtrees.lan.paternostro.priv/data/app/Schema/Migration44.php(95): Illuminate\Database\Query
\Builder->insertUsing(Array, Object(Illuminate\Database\Query\Builder))`
`#5 /var/www/webtrees.lan.paternostro.priv/data/app/Services/MigrationService.php(69): Fisharebest\Webtrees\Schema
\Migration44->upgrade()`
`#6 /var/www/webtrees.lan.paternostro.priv/data/app/Http/RequestHandlers/SetupWizard.php(405):
Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 45)`
`#7 /var/www/webtrees.lan.paternostro.priv/data/app/Http/RequestHandlers/SetupWizard.php(366):
Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->createConfigFile(Array)`
`#8 /var/www/webtrees.lan.paternostro.priv/data/app/Http/RequestHandlers/SetupWizard.php(200):
Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->step6Install(Array)`
`#9 /var/www/webtrees.lan.paternostro.priv/data/app/Http/Middleware/ReadConfigIni.php(69): Fisharebest\Webtrees
\Http\RequestHandlers\SetupWizard->handle(Object(Nyholm\Psr7\ServerRequest))`
`#10 /var/www/webtrees.lan.paternostro.priv/data/vendor/oscarotero/middleland/src/Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest),
Object(Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard))`
`#11 /var/www/webtrees.lan.paternostro.priv/data/app/Http/Middleware/SecurityHeaders.php(47):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))`
`#12 /var/www/webtrees.lan.paternostro.priv/data/vendor/oscarotero/middleland/src/Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher))`
`#13 /var/www/webtrees.lan.paternostro.priv/data/app/Http/Middleware/EmitResponse.php(57):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))`
`#14 /var/www/webtrees.lan.paternostro.priv/data/vendor/oscarotero/middleland/src/Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher))`
`#15 /var/www/webtrees.lan.paternostro.priv/data/app/Http/Middleware/PhpEnvironment.php(49):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))`
`#16 /var/www/webtrees.lan.paternostro.priv/data/vendor/oscarotero/middleland/src/Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher))`
`#17 /var/www/webtrees.lan.paternostro.priv/data/vendor/oscarotero/middleland/src/Dispatcher.php(118):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))`
`#18 /var/www/webtrees.lan.paternostro.priv/data/index.php(57): Middleland\Dispatcher->dispatch(Object(Nyholm
\Psr7\ServerRequest))`
`#19 {main}`

AFAIK, problem is related to lines 90 and 91 of [Migration44.php](https://github.com/fisharebest/webtrees/blob/master/app/Schema/Migration44.php), but I don't know how to solve in a database-independent way.

**Comment by upaternostro** [comment]
Please see [fix_pgsql_wrong_datatype](https://github.com/upaternostro/webtrees/tree/fix_pgsql_wrong_datatype)
