### ISSUE TITLE
Error while updating with Upgrade wizard

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3764]
`Copy files…
Uncaught Error: Undefined class constant 'PREF_TREE_DEFAULT_XREF' in /home/xxx/domains/xxx/public_html/app/Tree.php:587 Stack trace: #0 /home/xxx/domains/xxx/public_html/app/Module/ChartsMenuModule.php(94): Fisharebest\Webtrees\Tree->significantIndividual(Object(Fisharebest\Webtrees\User), '') #1 /home/xxx/domains/xxx/public_html/app/Module/ModuleThemeTrait.php(484): Fisharebest\Webtrees\Module\ChartsMenuModule->getMenu(Object(Fisharebest\Webtrees\Tree)) #2 [internal function]: class@anonymous::Fisharebest\Webtrees\Module\{closure}(Object(Fisharebest\Webtrees\Module\ChartsMenuModule), 'charts-menu') #3 /home/xxx/domains/xxx/public_html/vendor/illuminate/support/Collection.php(1120): array_map(Object(Closure), Array, Array) #4 /home/xxx/domains/xxx/public_html/app/Module/ModuleThemeTrait.php(485): Illuminate\Support\Collection->map(Object(Closure)) #5 /home/xxx/domains/xxx/public_html/resources/views/layouts/default.phtml(116): class

/home/xxx/domains/xxx/public_html/app/Tree.php: 587`

**Comment by mrqd9** [comment]
But updated successfully
