### ISSUE TITLE
bug: sqlite backend seems to be broken in versions newer than 2.0.11 

### ISSUE THREAD

**Issue by jsteuer** [fisharebest/webtrees#3822]
Hello. I am using webtrees 2.0.11 in combination with sqlite. The upgrading routine (to Version 2.0.15 now) runs into trouble:

```
PDOException: SQLSTATE[HY000]: General error: 1 near "as": syntax error in /volume1/applications/webtrees/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79
Stack trace:
#0 /volume1/applications/webtrees/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(79): PDO->prepare('update "wt_plac...', Array)
#1 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(479): Doctrine\DBAL\Driver\PDOConnection->prepare('update "wt_plac...')
#2 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('update "wt_plac...', Array)
#3 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('update "wt_plac...', Array, Object(Closure))
#4 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(490): Illuminate\Database\Connection->run('update "wt_plac...', Array, Object(Closure))
#5 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(423): Illuminate\Database\Connection->affectingStatement('update "wt_plac...', Array)
#6 /volume1/applications/webtrees/vendor/illuminate/database/Query/Builder.php(2721): Illuminate\Database\Connection->update('update "wt_plac...', Array)
#7 /volume1/applications/webtrees/app/Schema/Migration44.php(80): Illuminate\Database\Query\Builder->update(Array)
#8 /volume1/applications/webtrees/app/Services/MigrationService.php(71): Fisharebest\Webtrees\Schema\Migration44->upgrade()
#9 /volume1/applications/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(56): Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 45)
#10 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 /volume1/applications/webtrees/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#12 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 /volume1/applications/webtrees/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 /volume1/applications/webtrees/app/Http/Middleware/BadBotBlocker.php(219): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#17 /volume1/applications/webtrees/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#18 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#19 /volume1/applications/webtrees/app/Http/Middleware/RegisterFactories.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#20 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#21 /volume1/applications/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#22 /volume1/applications/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#23 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 /volume1/applications/webtrees/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#25 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#26 /volume1/applications/webtrees/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#27 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 /volume1/applications/webtrees/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#29 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 /volume1/applications/webtrees/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#31 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 /volume1/applications/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#34 /volume1/applications/webtrees/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#35 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#36 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#37 /volume1/applications/webtrees/index.php(57): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#38 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[HY000]: General error: 1 near "as": syntax error in /volume1/applications/webtrees/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /volume1/applications/webtrees/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(84): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(479): Doctrine\DBAL\Driver\PDOConnection->prepare('update "wt_plac...')
#2 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('update "wt_plac...', Array)
#3 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('update "wt_plac...', Array, Object(Closure))
#4 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(490): Illuminate\Database\Connection->run('update "wt_plac...', Array, Object(Closure))
#5 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(423): Illuminate\Database\Connection->affectingStatement('update "wt_plac...', Array)
#6 /volume1/applications/webtrees/vendor/illuminate/database/Query/Builder.php(2721): Illuminate\Database\Connection->update('update "wt_plac...', Array)
#7 /volume1/applications/webtrees/app/Schema/Migration44.php(80): Illuminate\Database\Query\Builder->update(Array)
#8 /volume1/applications/webtrees/app/Services/MigrationService.php(71): Fisharebest\Webtrees\Schema\Migration44->upgrade()
#9 /volume1/applications/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(56): Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 45)
#10 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 /volume1/applications/webtrees/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#12 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 /volume1/applications/webtrees/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 /volume1/applications/webtrees/app/Http/Middleware/BadBotBlocker.php(219): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#17 /volume1/applications/webtrees/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#18 /volume1/applications/webtrees/vendor/oscarotero…
```

I tried installing a fresh instance. With sqlite backend too. All versions newer than 2.0.11 seems to be broken:

```
SQLSTATE[HY000]: General error: 1 near "as": syntax error (SQL: update "wt_placelocation" as "wt_pl1" set "pl_parent_id" = 0 where "rowid" in (select "wt_pl1"."rowid" from "wt_placelocation" as "wt_pl1" left join "wt_placelocation" as "wt_pl2" on "wt_pl1"."pl_parent_id" = "wt_pl2"."pl_id" where "wt_pl2"."pl_id" is null))

#0 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('update "wt_plac...', Array, Object(Closure))
#1 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(490): Illuminate\Database\Connection->run('update "wt_plac...', Array, Object(Closure))
#2 /volume1/applications/webtrees/vendor/illuminate/database/Connection.php(423): Illuminate\Database\Connection->affectingStatement('update "wt_plac...', Array)
#3 /volume1/applications/webtrees/vendor/illuminate/database/Query/Builder.php(2721): Illuminate\Database\Connection->update('update "wt_plac...', Array)
#4 /volume1/applications/webtrees/app/Schema/Migration44.php(80): Illuminate\Database\Query\Builder->update(Array)
#5 /volume1/applications/webtrees/app/Services/MigrationService.php(71): Fisharebest\Webtrees\Schema\Migration44->upgrade()
#6 /volume1/applications/webtrees/app/Http/RequestHandlers/SetupWizard.php(405): Fisharebest\Webtrees\Services\MigrationService->updateSchema('\\Fisharebest\\We...', 'WT_SCHEMA_VERSI...', 45)
#7 /volume1/applications/webtrees/app/Http/RequestHandlers/SetupWizard.php(366): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->createConfigFile(Array)
#8 /volume1/applications/webtrees/app/Http/RequestHandlers/SetupWizard.php(200): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->step6Install(Array)
#9 /volume1/applications/webtrees/app/Http/Middleware/ReadConfigIni.php(69): Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard->handle(Object(Nyholm\Psr7\ServerRequest))
#10 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Http\RequestHandlers\SetupWizard))
#11 /volume1/applications/webtrees/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#12 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 /volume1/applications/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 /volume1/applications/webtrees/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#17 /volume1/applications/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#18 /volume1/applications/webtrees/index.php(57): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#19 {main}
```

It would be great, if you can fix this bug :)

**Comment by fisharebest** [comment]
Which version of SQLite do you use?

You can see this in the "Server information" section in the control panel.

**Comment by jsteuer** [comment]
SQLite version 3.10.2. 
(Pretty old version... I am using a disk station DS918+ with DSM 6.2.3-25426 Update 3 and PHP 7.4.9. As far as i see there is no official way to upgrade SQLite)

**Comment by fisharebest** [comment]
We use the database abstraction layer from laravel - so this SQL is not created by us, and therefore we cannot fix it.

The [documentation](https://laravel.com/docs/8.x/database#sqlite-configuration) says that SQLite 3.8.8 or higher is required.

Perhaps that documentation is outdated?

FYI, we run a clean install as part of our test scripts. So, the 2.0 branch runs whatever SQLite version is included in ubuntu 20.04 builds of PHP 7.1 -> 7.4.

**Comment by jsteuer** [comment]
Ok, thank you very much!  So I'm going to switch to PostgreSQL...

**Comment by fisharebest** [comment]
FYI, postgres does not provide support for locale-aware sorting/searching.  So some features don't work 100% with Postgres.

If you have a choice, then MySQL / MariaDB is recommended...
