### ISSUE TITLE
Deleting an inactive user results in error message and doesn't work

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3850]
I'm not able to use the function "delete inactive user". There is a test user who was never registered ("User didn’t verify within 7 days. User not verified by administrator.").
```
Argument 1 passed to Fisharebest\Webtrees\Services\UserService::find() must be of the type int or null, string given, called in …/app/Http/RequestHandlers/UsersCleanupAction.php on line 63 …/app/Services/UserService.php:53
#0 …/app/Http/RequestHandlers/UsersCleanupAction.php(63): Fisharebest\Webtrees\Services\UserService->find()
#1 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\UsersCleanupAction->handle()
#2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#3 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(226): Middleland\Dispatcher->handle()
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process()
#5 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle()
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process()
#7 …/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(169): Middleland\Dispatcher->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->process()
#9 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#11 …/app/Http/Middleware/AuthAdministrator.php(52): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthAdministrator->process()
#13 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#16 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher->dispatch()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#18 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#20 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
```

**Comment by hartenthaler** [comment]
When using "user administration" instead of "delete inactive users" I was able to successfully delete this user.
