### ISSUE TITLE
Fatal error: Control panel - manage media

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3945]
At commit https://github.com/fisharebest/webtrees/commit/c74ea67da20897a055de168780603a11e4f0594d

Error message displayed on attempting to manage media from control panel

Two things to note:
Database is not corrupt and table wt_media has column m_file.
I ran composer update --no-dev after rebasing to latest commit

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'wt_media.m_file' in 'on clause' (SQL: select COALESCE(setting_value, 'media/') || multimedia_file_refn AS path from `wt_media_file` left join `wt_gedcom_setting` on `wt_gedcom_setting`.`gedcom_id` = `wt_media`.`m_file` and `setting_name` = MEDIA_DIRECTORY where `multimedia_file_refn` NOT LIKE http://% and `multimedia_file_refn` NOT LIKE https://%) …\vendor\illuminate\database\Connection.php:692
#0 …\vendor\illuminate\database\Connection.php(652): Illuminate\Database\Connection->runQueryCallback('select COALESCE...', Array, Object(Closure))
#1 …\vendor\illuminate\database\Connection.php(360): Illuminate\Database\Connection->run('select COALESCE...', Array, Object(Closure))
#2 …\vendor\illuminate\database\Query\Builder.php(2351): Illuminate\Database\Connection->select('select COALESCE...', Array, true)
#3 …\vendor\illuminate\database\Query\Builder.php(2595): Illuminate\Database\Query\Builder->runSelect()
#4 …\vendor\illuminate\database\Query\Builder.php(2905): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 …\vendor\illuminate\database\Query\Builder.php(2597): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 …\app\Services\MediaFileService.php(347): Illuminate\Database\Query\Builder->pluck('path')
#7 …\app\Http\RequestHandlers\ManageMediaPage.php(63): Fisharebest\Webtrees\Services\MediaFileService->allMediaFolders(Object(League\Flysystem\Filesystem))
#8 …\app\Http\Middleware\RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ManageMediaPage->handle(Object(Nyholm\Psr7\ServerRequest))
...
```

**Comment by fisharebest** [comment]
It looks like some investigatory code got committed by mistake.

I'll revert it.
