### ISSUE TITLE
Error when I hit a date - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#4183]
When I hit on a date in demo-dev or on my test system, I see an error

Argument 1 passed to Fisharebest\Webtrees\Date::display() must be an instance of Fisharebest\Webtrees\Tree or null, bool given, called in …/app/Module/ShareAnniversaryModule.php on line 119 …/app/Date.php:250
#0 …/app/Module/ShareAnniversaryModule.php(119): Fisharebest\Webtrees\Date->display()
#1 …/vendor/illuminate/collections/Collection.php(742): Fisharebest\Webtrees\Module\ShareAnniversaryModule->Fisharebest\Webtrees\Module\{closure}()
#2 …/app/Module/ShareAnniversaryModule.php(120): Illuminate\Support\Collection->mapWithKeys()
#3 …/app/Http/RequestHandlers/IndividualPage.php(130): Fisharebest\Webtrees\Module\ShareAnniversaryModule->share()
#4 [internal function]: Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->Fisharebest\Webtrees\Http\RequestHandlers\{closure}()
#5 …/vendor/illuminate/collections/Collection.php(695): array_map()
#6 …/app/Http/RequestHandlers/IndividualPage.php(130): Illuminate\Support\Collection->map()
etc.

**Comment by melizaa** [comment]
Same as #4182
