### ISSUE TITLE
BindingResolutionException on new install

### ISSUE THREAD

**Issue by causa-prima** [fisharebest/webtrees#4192]
I get the following exception when on a fresh install of 2.0.19 as well as on 2.0.16 before even getting any pages:
```
[29-Jan-2022 17:19:24] WARNING: [pool www] child 31733 said into stderr: "[29-Jan-2022 16:19:24 UTC] PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [PsrExt\Http\Message\ServerRequestFactoryInterface] is not instantiable while building [Nyholm\Psr7Server\ServerRequestCreator]. in /var/www/virtual/[mylocation]/vendor/illuminate/container/Container.php:960"
[29-Jan-2022 17:19:24] WARNING: [pool www] child 31733 said into stderr: "Stack trace:"
[29-Jan-2022 17:19:24] WARNING: [pool www] child 31733 said into stderr: "#0 /var/www/virtual/[mylocation]/vendor/illuminate/container/Container.php(794): Illuminate\Container\Container->notInstantiable('PsrExt\\Http\\Mes...')"
[29-Jan-2022 17:19:24] WARNING: [pool www] child 31733 said into stderr: "#1 /var/www/virtual/[mylocation]/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('PsrExt\\Http\\Mes...')"
[29-Jan-2022 17:19:24] WARNING: [pool www] child 31733 said into stderr: "#2 /var/www/virtual/[mylocation]/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('PsrExt\\Http\\Mes...', Array)"
[29-Jan-2022 17:19:24] WARNING: [pool www] child 31733 said into stderr: "#3 /var/www/virtual/[mylocation]/vendor/illuminate/container/Container.php(927): Illuminate\Container\Container->make('PsrExt\\Http\\Mes...')"
[29-Jan-2022 17:19:24] WARNING: [pool www] child 31733 said into stderr: "#4 /var/www/virtual/[mylocation]. in /var/www/virtual/[mylocation]/vendor/illuminate/container/Container.php on line 960"
```
As far as I remember, it used to work for some time, so maybe my hoster changed some PHP settings or something. What might be the issue? What can I check?

**Comment by fisharebest** [comment]
The error suggests you have either an incomplete installation, or a mix of files from two different versions.

**Comment by causa-prima** [comment]
Thanks for the swift reply! I'm not sure how that might happen, as I just followed the installation guide, unzipping the archive to an empty folder, resulting in 1003 directories and 9074 files. Just to be sure, I retried again:
1. Deleted the old folder.
2. Unzipped the zip file.
Still, the same exception is thrown. What could I do to pinpoint the missing files or any other cause?

**Comment by causa-prima** [comment]
I created a list of all files in the directory using `ls -R`: [webtree-files.txt](https://github.com/fisharebest/webtrees/files/7964267/webtree-files.txt)

**Comment by Art4** [comment]
Hey :wave: 
I received this exaclty same error today out of nowhere. I'm running webtrees 2.0.17 and havn't changed anything on my server.

**Comment by causa-prima** [comment]
@Art4: Are you by any chance hosting webtrees on uberspace like I do? If so, it's probably best to contact them, as the probably changed something. If not, at least I'm not alone.

**Comment by Art4** [comment]
Yes, I'm hosting on uberspace, too. So maybe they changed something on the server.

**Comment by causa-prima** [comment]
Great, so probably they changed something. I asked them for help with a reference to this ticket. If I'm able to fix it, I'll let you know here.

**Comment by causa-prima** [comment]
I got a response that lead me to a fix: use php 8.0.

**Comment by fisharebest** [comment]
Which version of PHP were you using?

**Comment by Art4** [comment]
I can confirm that switching from PHP 7.4.27 to 8.0.15 resolved the issue.

**Comment by causa-prima** [comment]
I was using 7.4 as well (same shared hoster, as stated earlier).

**Comment by bmarwell** [comment]
@fisharebest and I debugged webtrees 2.0.x and found out that PHP 7.4 ships a psr.so module on Uberspace. Support is notified: https://twitter.com/bmarwell/status/1507282586871205888?s=20&t=S2D7QCXyVTr_kLLkZq8fnA

**Comment by fisharebest** [comment]
See https://github.com/jbboehr/php-psr/issues/88
