### ISSUE TITLE
e-mail address error

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4377]
After a manual upgrade of my test server to 2.1.2 I found this error. I had never configured the email in the control panel on that website. After selecting "SMTP" instead of "sendmail", this error disappeared.
```
Email "" does not comply with addr-spec of RFC 2822. …/vendor/symfony/mime/Address.php:56
#0 …/app/Services/EmailService.php(102): Symfony\Component\Mime\Address->__construct()
#1 …/app/Services/EmailService.php(69): Fisharebest\Webtrees\Services\EmailService->message()
#2 …/app/Module/ReviewChangesModule.php(141): Fisharebest\Webtrees\Services\EmailService->send()
#3 …/resources/views/user-page-block.phtml(18): Fisharebest\Webtrees\Module\ReviewChangesModule->getBlock()
#4 …/app/View.php(183): include('...')
#5 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#6 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#7 …/resources/views/user-page.phtml(28): view()
#8 …/app/View.php(183): include('...')
#9 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#10 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#11 …/app/Http/ViewResponseTrait.php(50): view()
#12 …/app/Http/RequestHandlers/UserPage.php(84): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->viewResponse()
```

**Comment by fisharebest** [comment]
webtrees is trying to send an email.  Possibly to tell you about pending changes.

I guess you did not configure the "From email" in the mail settings.
