### ISSUE TITLE
Error Thrown After Back Button

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4449]
I started adding a Census to an individual, accidentally clicked the Cancel button.  From the individual page, I clicked the browser's back button, then completed the Census.

webtrees threw:

```
Undefined offset: 26 …/app/Services/GedcomEditService.php:153
#0 …/app/Services/GedcomEditService.php(153): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/Http/RequestHandlers/EditFactAction.php(76): Fisharebest\Webtrees\Services\GedcomEditService->editLinesToGedcom()
#2 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\EditFactAction->handle()
#3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
```

**Comment by miqrogroove** [comment]
Seems to involve other variables than what I described.  Not worth testing more at this time.
