### ISSUE TITLE
PHP Fatal error:  Uncaught Fisharebest\Webtrees\Http\Exceptions\HttpBadRequestException: Der Parameter „route“ fehlt.

### ISSUE THREAD

**Issue by mpwt** [fisharebest/webtrees#4548]
I found some actual error messages in an error log file in the root folder of webtrees. There is no error message within webtrees. 

Could it be that this has something to do with PHP 8.1? I got the error message only after switching to webtrees 2.1.7 and PHP 8.1?
At the moment I'm testing PHP 8.0 to see if the error also occurs there.

error message:
```
[05-Sep-2022 07:51:07 UTC] PHP Fatal error:  Uncaught Fisharebest\Webtrees\Http\Exceptions\HttpBadRequestException: Der Parameter „route“ fehlt. in /[replaced]/app/Validator.php:318
Stack trace:
#0 /[replaced]/resources/views/layouts/default.phtml(67): Fisharebest\Webtrees\Validator->route()
#1 /[replaced]/app/View.php(183): include('/home/bauschaf/...')
#2 /[replaced]/app/View.php(278): Fisharebest\Webtrees\View->render()
#3 /[replaced]/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#4 /[replaced]/app/Http/ViewResponseTrait.php(54): view()
#5 /[replaced]/app/Http/Middleware/HandleExceptions.php(171): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->viewResponse()
#6 /[replaced]/app/Http/Middleware/HandleExceptions.php(99): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->httpExceptionResponse()
#7 /[replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#8 /[replaced]/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle()
#9 /[replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#10 /[replaced]/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#11 /[replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#12 /[replaced]/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#13 /[replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#14 /[replaced]/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#15 /[replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#16 /[replaced]/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#17 /[replaced]/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#18 /[replaced]/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#19 /[replaced]/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#20 {main}
  thrown in /[replaced]/app/Validator.php on line 318
```

**Comment by fisharebest** [comment]
I'm using 8.1 in my dev environment, so I don't think this is related.

The "page template" includes the name of the current route (i.e. URL).
e.g. `<body class="wt-route-login-page">`

This is to allow CSS rules to target specific pages.

The error says that we are trying to display a page, but the route is not defined.

The only way I can think this would happen is if an error occured before we match the route - and that this error is occuring when we try to create a pretty display for the original error.

All the reports say that this does not happen for interactive users - only for robots/crawlers/etc.

Can you match the date/time of the error with the HTTP request from your webserver logs?
Is there a pattern?

**Comment by mpwt** [comment]
You are right. For the times of error messages, it is always/mostly crawlers and bots. 

I only noticed these error messages with webtrees 2.1. Can/should they be ignored?

<img width="1352" alt="Bildschirmfoto 2022-09-05 um 13 49 41" src="https://user-images.githubusercontent.com/16311627/188442482-1dcbd923-b882-4207-acec-2fc51acf3845.png">

**Comment by mpwt** [comment]
There is no traceable system of error messages. There are currently several entries on 10.09., one on 12.09. and one on 17.09.. I therefore close the issue at the moment. Thank you for your support.

**Comment by Bagu** [comment]
Hello,

I have the same problem
```
[10-Oct-2022 22:30:03 UTC] PHP Fatal error:  Uncaught Fisharebest\Webtrees\Http\Exceptions\HttpBadRequestException: Le paramètre « route » est manquant. in \app\Validator.php:318
Stack trace:
#0 E:\www\wwwbagubiz\html\genealogie\resources\views\layouts\default.phtml(67): Fisharebest\Webtrees\Validator->route()
#1 \app\View.php(183): include('...')
#2 \app\View.php(278): Fisharebest\Webtrees\View->render()
#3 \app\Helpers\functions.php(145): Fisharebest\Webtrees\View::make()
#4 \app\Http\ViewResponseTrait.php(54): view()
#5 \app\Http\Middleware\HandleExceptions.php(171): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->viewResponse()
#6 \app\Http\Middleware\HandleExceptions.php(99): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->httpExceptionResponse()
#7 \vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#8 \app\Http\Middleware\BaseUrl.php(79): Middleland\Dispatcher->handle()
#9 \vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#10 \app\Http\Middleware\ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#11 \vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#12 \app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#13 \vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#14 \app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher->handle()
#15 \vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#16 \vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle()
#17 \app\Webtrees.php(275): Middleland\Dispatcher->dispatch()
#18 \app\Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#19 \index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#20 {main}
  thrown in \app\Validator.php on line 318
```
It happen when bing bot crawl my website. (once a week) or google bot (once a week too, but not the same day)
It make my logs full or craps.
Is there a way to avoid this ?

**Comment by fisharebest** [comment]
This error is only shown to robots.  It means "there was an earlier error, and we are not able to display it".

So, we must learn this earlier error.

If you can provide full details of the HTTP request that causes the error, I may be able to investigate.

**Comment by fisharebest** [comment]
Thanks for the logs.

A `POST` request to `/` (or any URL that does not expect `POST`) will trigger the error.

BTW - In your logs, I see that this IP address also tries to fetch `/.env`, which contains usernames/passwords on many systems.  The IP address seems to belong to Microsoft.  Perhaps someone/something at Microsoft is trying to hack your server...

**Comment by FrankWarius** [comment]
>  In your logs, I see that this IP address also tries to fetch `/.env`, which ...
I recently adopted your .htacces recommendations from https://webtrees.net/faq/urls/. In doing so I have 
`RewriteRule \.git - [F] `
on all <root> . directories (e.g. .vscode, well-known) extended,
This is the web.config:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <clear />
                <rule name="HTTPS Redirect" enabled="true" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false">
                        <add input="{HTTPS}" pattern="^OFF$" />
                    </conditions>
                    <action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" appendQueryString="false" redirectType="Permanent" />
                </rule>
                <rule name="Webtrees .git etc" enabled="true" stopProcessing="true">
                    <match url="^\." ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false">
                    </conditions>
                    <action type="CustomResponse" statusCode="403" statusReason="Forbidden - internal config" statusDescription="Forbidden" />
                </rule>
                <rule name="Webtrees data">
                    <match url="^data(/|$)" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="CustomResponse" statusCode="403" statusReason="Forbidden" statusDescription="Forbidden" />
                </rule>
                <rule name="Webtrees app">
                    <match url="^app(/|$)" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="CustomResponse" statusCode="403" statusReason="Forbidden" statusDescription="Forbidden" />
                </rule>
                <rule name="Webtrees modules">
                    <match url="^modules" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="CustomResponse" statusCode="403" statusReason="Forbidden" statusDescription="Forbidden" />
                </rule>
                <rule name="Webtrees resources">
                    <match url="^resources(/|$)" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="CustomResponse" statusCode="403" statusReason="Forbidden" statusDescription="Forbidden" />
                </rule>
                <rule name="Webtrees vendor">
                    <match url="^vendor(/|$)" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="CustomResponse" statusCode="403" statusReason="Forbidden" statusDescription="Forbidden" />
                </rule>
                <rule name="Webtrees route=" enabled="true" stopProcessing="true">
                    <match url="index\.php?" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAny" trackAllCaptures="false">
                        <add input="{QUERY_STRING}" pattern="route=(%2F|/)(.*)" ignoreCase="false" />
                    </conditions>
                    <action type="Redirect" url="/{C:2}" appendQueryString="false" logRewrittenUrl="true" />
                </rule>
                <rule name="Webtrees Rewrite" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false">
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php" />
                </rule>
            </rules>
        </rewrite>
```
