### ISSUE TITLE
Control panel / Website / GEDCOM tags

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4614]
When I try to click on "GEDCOM tags" the following error appears:
`ErrorException: Undefined variable $custom_fam_fact in /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/resources/views/admin/tags.phtml:983 Stack trace: #0 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/resources/views/admin/tags.phtml(983): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}() #1 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/View.php(183): include('...') #2 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/View.php(278): Fisharebest\Webtrees\View->render() #3 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() #4 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/modules_v4/vesta_classic_look_and_feel/resources/views/admin/tags-ext.phtml(16): view() #5 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/View.php(183): include('...') #6 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/View.php(278): Fisharebest\Webtrees\View->render() #7 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() #8`

**Comment by fisharebest** [comment]
webtrees adds some additional configuration options in this release.

These allow some GEDCOM 7 features to be used.d

I guess the vesta module is replacing this config page, and also needs updating.
