### ISSUE TITLE
php 2.2.0-dev media error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4616]
for every media object on page, I get network error 500 with following error reported

```
League\Flysystem\PathPrefixing\PathPrefixedAdapter&quot; not found …\app\Factories\FilesystemFactory.php:52
#0 …\app\Tree.php(596): Fisharebest\Webtrees\Factories\FilesystemFactory-&gt;data(&#039;media/&#039;)
#1 …\app\Factories\ImageFactory.php(208): Fisharebest\Webtrees\Tree-&gt;mediaFilesystem()
#2 …\app\Http\RequestHandlers\MediaFileThumbnail.php(83): Fisharebest\Webtrees\Factories\ImageFactory-&gt;mediaFileThumbnailResponse(Object(Fisharebest\Webtrees\MediaFile), 200, 260, &#039;crop&#039;, false)
#3 …\app\Http\Middleware\RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\MediaFileThumbnail-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#4 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#5 …\app\Module\HitCountFooterModule.php(154): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#6 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#7 …\app\Module\CheckForNewVersion.php(115): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#8 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#9 …\app\Http\Middleware\CheckCsrf.php(80): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#10 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#12 …\app\Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest))
#13 …\app\Http\Middleware\Router.php(152): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#14 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 …\app\Http\Middleware\BootModules.php(60): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#16 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#17 …\app\Http\Middleware\RegisterGedcomTags.php(54): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#18 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#19 …\app\Http\Middleware\LoadRoutes.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#20 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#21 …\app\Http\Middleware\CheckForNewVersion.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#22 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#23 …\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#24 …\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#25 …\app\Http\Middleware\UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction(Object(Closure), 3)
#26 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#27 …\app\Http\Middleware\DoHousekeeping.php(73): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#28 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#29 …\app\Http\Middleware\UseTheme.php(69): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#30 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#31 …\app\Http\Middleware\CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#32 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#33 …\app\Http\Middleware\UseLanguage.php(71): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#34 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#35 …\app\Http\Middleware\UseSession.php(78): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#36 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#37 …\app\Http\Middleware\UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#38 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#39 …\app\Http\Middleware\UseDatabase.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#40 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#41 …\app\Http\Middleware\BadBotBlocker.php(245): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#42 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#43 …\app\Http\Middleware\CompressResponse.php(73): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#44 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#45 …\app\Http\Middleware\ContentLength.php(40): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#46 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#47 …\vendor\middlewares\client-ip\src\ClientIp.php(65): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#48 …\app\Http\Middleware\ClientIp.php(47): Middlewares\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#49 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#50 …\app\Http\Middleware\HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#51 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#52 …\app\Http\Middleware\BaseUrl.php(73): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#53 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#54 …\app\Http\Middleware\ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#55 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#56 …\app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#57 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#58 …\app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#59 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#60 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
#61 …\app\Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest))
#62 …\app\Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#63 …\index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest()
```

**Comment by fisharebest** [comment]
In 2.2, there are lots of updated libraries.

You need to run `composer install`.

**Comment by ddrury** [comment]
oops
