### ISSUE TITLE
Version 2.1.8: Error Language

### ISSUE THREAD

**Issue by heiler** [fisharebest/webtrees#4618]
```
Fisharebest\Webtrees\I18N::language(): Return value must be of type Fisharebest\Webtrees\Module\ModuleLanguageInterface, null returned …/app/I18N.php:392 
#0 …/app/Module/IndividualListModule.php(559): Fisharebest\Webtrees\I18N::language() 
#1 …/app/Module/IndividualListModule.php(304): Fisharebest\Webtrees\Module\IndividualListModule-&gt;surnameAlpha() #2 …/app/Module/IndividualListModule.php(163): Fisharebest\Webtrees\Module\IndividualListModule-&gt;createResponse() 
#3 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Module\IndividualListModule-&gt;handle() 
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() 
#5 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher-&gt;handle() 
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion-&gt;process() 
#7 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher-&gt;handle() 
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() 
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() 
#10 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch() 
#11 …/app/Http/Middleware/Router.php(152): Fisharebest\Webtrees\Webtrees::dispatch() 
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() 
#13 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher-&gt;handle() 
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process() 
#15 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher-&gt;handle() 
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags-&gt;process() 
#17 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher-&gt;handle() 
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process() 
#19 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher-&gt;handle() 
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion-&gt;process() 
#21 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle() 
#22 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() 
#23 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction() 
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process() 
#25 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher-&gt;handle() 
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process() 
#27 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher-&gt;handle() 
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process() 
#29 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle() 
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process() 
#31 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher-&gt;handle() 
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() 
#33 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher-&gt;handle() 
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() 
#35 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle() 
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() 
#37 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher-&gt;handle() 
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() 
#39 …/app/Http/Middleware/BadBotBlocker.php(245): Middleland\Dispatcher-&gt;handle() 
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() 
#41 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher-&gt;handle() 
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() 
#43 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle() 
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process() 
#45 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle() 
#46 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() 
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() 
#48 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle() 
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() 
#50 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher-&gt;handle() 
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() 
#52 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle() 
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process() 
#54 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle() 
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() 
#56 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() 
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() 
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #
59 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch() 
#60 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() 
#61 …/index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() 
#62 {main}
```

**Comment by fisharebest** [comment]
Is this for every page?  Just some pages?

**Comment by heiler** [comment]
Family List and Individual List are concerned.  I found 5 errors in my log, but cannot reproduce the problem.

**Comment by fisharebest** [comment]
In your logs, can you see if this was a robot/crawler or a real user?

**Comment by heiler** [comment]
Maybe this is the reason, all bad boys:
62.138.2.14  startdedicated
64.124.8.59  above.net
64.124.8.35  above.net

**Comment by fisharebest** [comment]
Probably malformed requests.

If it happens again/regularly, we could add some logging to see exactly what they are doing.

But othewise, I think we can ignore this.
