### ISSUE TITLE
Class Finfo not found on PHP 8.0 and 8.1

### ISSUE THREAD

**Issue by rhengles** [fisharebest/webtrees#4632]
When I use PHP version 7.4, the site works. When I change the PHP version to 8.0 or 8.1, the home page also works but the "admin" page breaks with the error below:

I recently updated webtrees from 1.8.x to 2.1.9. I just downloaded the zip file from website and uploaded all the files to my server as instructed on the docs.

```
Class "finfo" not found …/vendor/league/mime-type-detection/src/FinfoMimeTypeDetector.php:48
```

<details>
  <summary>
    Full stack trace:
  </summary>

  ```
#0 …/vendor/league/flysystem/src/Local/LocalFilesystemAdapter.php(96): League\MimeTypeDetection\FinfoMimeTypeDetector->__construct()
#1 …/app/Http/RequestHandlers/ControlPanel.php(137): League\Flysystem\Local\LocalFilesystemAdapter->__construct()
#2 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel->handle()
#3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#4 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#6 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#8 …/app/Http/Middleware/AuthAdministrator.php(53): Middleland\Dispatcher->handle()
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthAdministrator->process()
#10 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#13 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#14 …/app/Http/Middleware/Router.php(152): Fisharebest\Webtrees\Webtrees::dispatch()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#16 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#18 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#20 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#22 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#24 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#25 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#26 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#28 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#30 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#32 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#34 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#36 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#38 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#40 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#42 …/app/Http/Middleware/BadBotBlocker.php(245): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#44 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#46 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#48 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#49 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#51 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#53 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#55 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#57 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#59 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#62 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#63 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#64 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#65 {main}
  ```
</details>

**Comment by rhengles** [comment]
This answer solved it for me:

https://stackoverflow.com/a/71504825

I had to enable the 'fileinfo' extension in cpanel.
