### ISSUE TITLE
After auto-upgrade: nothing works

### ISSUE THREAD

**Issue by someone-somenet-org** [fisharebest/webtrees#4635]
Just got the email that a new version is available.

After "successfully" upgrading nothing works and all pages only show this stack trace

```
ParseError: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in /var/www/vhost/app/Http/Middleware/BadBotBlocker.php:350 Stack trace: #0 /var/www/vhost/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile() #1 [internal function]: Composer\Autoload\ClassLoader->loadClass() #2 [internal function]: spl_autoload_call() #3 /var/www/vhost/vendor/illuminate/container/Container.php(877): ReflectionClass->__construct() #4 /var/www/vhost/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build() #5 /var/www/vhost/vendor/illuminate/container/Container.php(705): Illuminate\Container\Container->resolve() #6 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(97): Illuminate\Container\Container->get() #7 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(126): Middleland\Dispatcher->get() #8 /var/www/vhost/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle() #9 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #10 /var/www/vhost/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #11 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #12 /var/www/vhost/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #13 /var/www/vhost/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #14 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #15 /var/www/vhost/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #16 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #17 /var/www/vhost/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle() #18 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #19 /var/www/vhost/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #20 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #21 /var/www/vhost/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #22 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #23 /var/www/vhost/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #24 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #25 /var/www/vhost/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #26 /var/www/vhost/app/Webtrees.php(275): Middleland\Dispatcher->dispatch() #27 /var/www/vhost/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #28 /var/www/vhost/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #29 {main}
```

The error is on this line, an exception variable is missing:
https://github.com/fisharebest/webtrees/blob/9d15b78eafc58b7682cca0e418e929d600dc2fb8/app/Http/Middleware/BadBotBlocker.php#L350

**Comment by someone-somenet-org** [comment]
also maybe you want to stop distributing the broken release, which breaks installations after auto-upgrading. :)
