### ISSUE TITLE
Update V2.1.7 -> V2.1.10: "Uncaught Error: Call to a member function connection() on null ..."

### ISSUE THREAD

**Issue by ungeahnt** [fisharebest/webtrees#4637]
I've tried it with php8.0 and php8.1 without success (= same error message).
All custom modules are deactivated.

`Uncaught Error: Call to a member function connection() on null in /home/www/proavitus.de/vendor/illuminate/database/Capsule/Manager.php:87 Stack trace:
#0 /home/www/proavitus.de/app/Site.php(152): Illuminate\Database\Capsule\Manager::table('site_setting')
#1 /home/www/proavitus.de/app/Http/Middleware/HandleExceptions.php(156): Fisharebest\Webtrees\Site::getPreference('DEFAULT_GEDCOM')
#2 /home/www/proavitus.de/app/Http/Middleware/HandleExceptions.php(99): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->httpExceptionResponse(Object(Nyholm\Psr7\ServerRequest), Object(Fisharebest\Webtrees\Http\Exceptions\HttpBadRequestException))
#3 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#4 /home/www/proavitus.de/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#5 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#6 /home/www/proavitus.de/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#7 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#8 /home/www/proavitus.de/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#9 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#10 /home/www/proavitus.de/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#11 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#12 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#13 /home/www/proavitus.de/app/Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#14 /home/www/proavitus.de/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#15 /home/www/proavitus.de/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#16 {main} thrown

/home/www/proavitus.de/vendor/illuminate/database/Capsule/Manager.php: 87`

also see https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37497-le-site-ne-fonctionne-pas-apres-mise-a-jour-2-1-8-ou-2-1-9-donc-retour-a-2-1-7

**Comment by fisharebest** [comment]
Firstly, there was a validation error.
Secondly, there is an error when displaying the first error.

Can you add the line `echo $exception->getTraceAsString();exit;` between these two lines

https://github.com/fisharebest/webtrees/blob/22006fb948449920bcb7c40cfd4d73ea1fe7c6da/app/Http/Middleware/HandleExceptions.php#L154-L155

**Comment by ungeahnt** [comment]
Updated to V2.1.11 and added the requested line in HandleExceptions.php:

`#0 [internal function]: Fisharebest\Webtrees\Validator::Fisharebest\Webtrees\{closure}('B\xF6hlen', 'REDIRECT_GEOIP_...')
#1 /home/www/proavitus.de/app/Validator.php(69): array_walk_recursive(Array, Object(Closure))
#2 /home/www/proavitus.de/app/Validator.php(112): Fisharebest\Webtrees\Validator->__construct(Array, Object(Nyholm\Psr7\ServerRequest))
#3 /home/www/proavitus.de/app/Http/Middleware/BadBotBlocker.php(198): Fisharebest\Webtrees\Validator::serverParams(Object(Nyholm\Psr7\ServerRequest))
#4 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#5 /home/www/proavitus.de/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#6 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#7 /home/www/proavitus.de/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#8 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#9 /home/www/proavitus.de/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#10 /home/www/proavitus.de/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#12 /home/www/proavitus.de/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#13 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#14 /home/www/proavitus.de/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#15 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#16 /home/www/proavitus.de/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#17 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 /home/www/proavitus.de/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#19 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 /home/www/proavitus.de/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#21 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 /home/www/proavitus.de/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#23 /home/www/proavitus.de/app/Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#24 /home/www/proavitus.de/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#25 /home/www/proavitus.de/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#26 {main}`

**Comment by fisharebest** [comment]
webtrees is validating all input data to make sure it is valid UTF-8.

This says that your server is setting an HTTP header `REDIRECT_GEOIP_…` which contains data that isn't valid UTF-8 - `B\xF6hlen`.

**Comment by ungeahnt** [comment]
1) Why this error happens only after the update > V2.1.7? 



2) `Böhlen`, but I've no idea about it. It's a city in Germany, far away from my location and the server location (as far as I know). Maybe it's connected in a different way with my webhoster? 

3) Is this `REDIRECT_GEOIP` added by the webhoster (=server) or by the internet provider?

**Comment by fisharebest** [comment]
> Why this error happens only after the update > V2.1.7?

Because webtrees now validates all parameters.

> Is this REDIRECT_GEOIP added by the webhoster (=server) or by the internet provider?

Yes.  It is added by the webserver.

I guess it is trying to detect the location of your IP address.

According to [RFC 7230](https://www.rfc-editor.org/rfc/rfc7230#section-1.2), HTTP headers can only contain ASCII characters.

So, this header is invalid - and the code is rejecting it (as expected).

But if ISPs are adding invalid characters, then I guess we need to allow them...

**Comment by ungeahnt** [comment]
Thanks a lot for the quick support!
