### ISSUE TITLE
Error vers. 2.1.11

### ISSUE THREAD

**Issue by heiler** [fisharebest/webtrees#4642]
```
PHP Fatal error:  Uncaught Fisharebest\\Webtrees\\Http\\Exceptions\\HttpBadRequestException: Der Parameter \xe2\x80\x9eroute\xe2\x80\x9c fehlt. in /htdocs/webtrees/app/Validator.php:322: /htdocs/webtrees/index.php
Stack trace:: /htdocs/webtrees/index.php
```

**Comment by fisharebest** [comment]
Try 2.1.12 which was released a few minutes ago.

**Comment by heiler** [comment]
The same error is in my provider's log with vers. 2.1.12.

**Comment by heiler** [comment]
You are right:

` Uncaught Fisharebest\\Webtrees\\Http\\Exceptions\\HttpBadRequestException: Der Parameter \xe2\x80\x9eroute\xe2\x80\x9c fehlt. in /htdocs/webtrees/app/Validator.php:333:`

**Comment by fisharebest** [comment]
> The same error is in my provider's log

You mean the apache log files (`error.log` and `access.log`).

Can you see the full details of the request.

Is it a human being or a robot/crawler?

**Comment by heiler** [comment]
Is it possible that these errors are displayed because of my local Matomo installation?

`POST /webtrees/XXXX/matomo/?module=API&format=csv&convertToUnicode=0&method=CoreAdminHome.runScheduledTasks&trigger=archivephp HTTP/1.1`

**Comment by fisharebest** [comment]
Do you have Matomo analytics installed?

**Comment by fisharebest** [comment]
This is not a webtrees URL.

Do your logs give the IP address where it originated?

Was this a valid user or a hacker?

**Comment by heiler** [comment]
The only visitor in the near was myself.

This is the complete error, I removed private data:

```
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: PHP Fatal error:  Uncaught Fisharebest\\Webtrees\\Http\\Exceptions\\HttpBadRequestException: Der Parameter \xe2\x80\x9eroute\xe2\x80\x9c fehlt. in /htdocs/webtrees/app/Validator.php:333: /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: Stack trace:: /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #0 /htdocs/webtrees/modules_v4/jc-theme-justlight/resources/views/layouts/default.phtml(47): Fisharebest\\Webtrees\\Validator->route(): //htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #1 /htdocs/webtrees/app/View.php(183): include('...'): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #2 /htdocs/webtrees/app/View.php(278): Fisharebest\\Webtrees\\View->render(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #3 /htdocs/webtrees/app/Helpers/functions.php(145): Fisharebest\\Webtrees\\View::make(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #4 /htdocs/webtrees/app/Http/ViewResponseTrait.php(54): view(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #5 /htdocs/webtrees/app/Http/Middleware/HandleExceptions.php(171): Fisharebest\\Webtrees\\Http\\Middleware\\HandleExceptions->viewResponse(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #6 /htdocs/webtrees/app/Http/Middleware/HandleExceptions.php(99): Fisharebest\\Webtrees\\Http\\Middleware\\HandleExceptions->httpExceptionResponse(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #7 /htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\\Webtrees\\Http\\Middleware\\HandleExceptions->process(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #8 /htdocs/webtrees/app/Http/Middleware/BaseUrl.php(73): Middleland\\Dispatcher->handle(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #9 /htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\\Webtrees\\Http\\Middleware\\BaseUrl->process(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #10 htdocs/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\\Dispatcher->handle(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #11 /htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\\Webtrees\\Http\\Middleware\\ReadConfigIni->process():/htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #12 /htdocs/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\\Dispatcher->handle(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #13 /htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\\Webtrees\\Http\\Middleware\\SecurityHeaders->process(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #14 /htdocs/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\\Dispatcher->handle(): /htdocs/webtrees/index.php
htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #16 /htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\\Dispatcher->handle(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #17 /htdocs/webtrees/app/Webtrees.php(275): Middleland\\Dispatcher->dispatch(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #18 /htdocs/webtrees/app/Webtrees.php(262): Fisharebest\\Webtrees\\Webtrees::dispatch(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #19 /htdocs/webtrees/index.php(51): Fisharebest\\Webtrees\\Webtrees->httpRequest(): /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215: #20 {main}: /htdocs/webtrees/index.php
06.12.2022 10:50:19 heiler-ahnen.de [client 2a01:238:200::] AH01215:   thrown in /htdocs/webtrees/app/Validator.php on line 333: /htdocs/webtrees/index.php
```

**Comment by fisharebest** [comment]
I guess that this URL should be sent to your Matomo installation.

Instead, it is being sent to webtrees.

I guess that you need to check your webserver configuration.

**Comment by heiler** [comment]
You can close this, it seems to be a problem of Pretty URL in connection with Matomo. I will try an exception rule in htaccess.
