### ISSUE TITLE
GEDCOM export not possible

### ISSUE THREAD

**Issue by LarsRabe** [fisharebest/webtrees#4653]
GEDCOM export gives error on dev 2.2 from dec 10, 2022
```
Class "League\Flysystem\PathPrefixing\PathPrefixedAdapter" not found …/app/Factories/FilesystemFactory.php:50
#0 …/app/Tree.php(596): Fisharebest\Webtrees\Factories\FilesystemFactory->data()
#1 …/app/Services/GedcomExportService.php(232): Fisharebest\Webtrees\Tree->mediaFilesystem()
#2 …/app/Services/GedcomExportService.php(121): Fisharebest\Webtrees\Services\GedcomExportService->export()
#3 …/app/Http/RequestHandlers/ExportGedcomClient.php(67): Fisharebest\Webtrees\Services\GedcomExportService->downloadResponse()
#4 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ExportGedcomClient->handle()
#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#6 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#8 …/app/Http/Middleware/AuthManager.php(54): Middleland\Dispatcher->handle()
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthManager->process()
#10 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#13 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#14 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#16 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#18 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#20 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#22 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#24 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#25 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#26 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#28 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#30 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#32 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#34 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#36 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#38 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#40 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#42 …/app/Http/Middleware/BadBotBlocker.php(278): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#44 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#46 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#48 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#49 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#51 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#53 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#55 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#57 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#59 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#62 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#63 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#64 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#65 {main}
```

**Comment by fisharebest** [comment]
If you are using the development code, you need to update your dependencies, using `composer install`.

There were many changes to the third-party libraries between 2.1 and 2.2 (main).
