### ISSUE TITLE
2.2 Dev Sqlsrv SeedUserTable  SQLSTATE[23000]: insert into [wt_user] IDENTITY_INSERTis OFF

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4667]
good job so far - almost done!
#0 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('insert into [wt...', Array, Object(Closure))
#1 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(546): Illuminate\Database\Connection->run('insert into [wt...', Array, Object(Closure))
#2 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(498): Illuminate\Database\Connection->statement('insert into [wt...', Array)
#3 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Query\Builder.php(3218): Illuminate\Database\Connection->insert('insert into [wt...', Array)
#4 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Query\Builder.php(3336): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\GitRepos\fisharebest\webtrees\app\Schema\SeedUserTable.php(40): Illuminate\Database\Query\Builder->updateOrInsert(Array, Array)
#6 D:\GitRepos\fisharebest\webtrees\app\Services\MigrationService.php(117): Fisharebest\Webtrees\Schema\SeedUserTable->run()
#7 D:\GitRepos\fisharebest\webtrees\app\Http\RequestHandlers\SetupWizard.php(399): Fisharebest\Webtrees\Services\MigrationService->seedDatabase()

**Comment by FrankWarius** [comment]
I found a fix and Config.ini,php is created, but now  get 
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Die implizite Konvertierung vom nvarchar-Datentyp in varbinary(max) ist nicht zulässig. Verwenden Sie die CONVERT-Funktion, um diese Abfrage auszuführen. (SQL: insert into [wt_session] ([session_id], [session_time], [user_id], [ip_address], [session_data]) values (r12cqpbo56d7cvssdj8t3mpbsd, 2022-12-16 22:47:04, 0, 127.0.0.1, initiated|b:1;))

#0 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('insert into [wt...', Array, Object(Closure))
#1 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(546): Illuminate\Database\Connection->run('insert into [wt...', Array, Object(Closure))
#2 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Connection.php(498): Illuminate\Database\Connection->statement('insert into [wt...', Array)
#3 D:\GitRepos\fisharebest\webtrees\vendor\illuminate\database\Query\Builder.php(3218): Illuminate\Database\Connection->insert('insert into [wt...', Array)
#4 D:\GitRepos\fisharebest\webtrees\app\SessionDatabaseHandler.php(100): Illuminate\Database\Query\Builder->insert(Array)
#5 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('r12cqpbo56d7cvs...', 'initiated|b:1;')
#6 D:\GitRepos\fisharebest\webtrees\app\Session.php(146): session_regenerate_id(false)

I'll push the fixes tommorow
