### ISSUE TITLE
db errors on 2.1.14 using experimental postgresql

### ISSUE THREAD

**Issue by elWyatt** [fisharebest/webtrees#4684]
errors in /var/log/postgresql:
```
2022-12-25 11:42:35.493 GMT [14295] webtreesadm@kanoma ERROR:  relation "wt_site_setting" does not exist at character 45
2022-12-25 11:42:35.493 GMT [14295] webtreesadm@kanoma STATEMENT:  select "setting_value", "setting_name" from "wt_site_setting"
2022-12-25 11:42:39.394 GMT [14319] webtreesadm@kanoma ERROR:  duplicate key value violates unique constraint "wt_module_pkey"
2022-12-25 11:42:39.394 GMT [14319] webtreesadm@kanoma DETAIL:  Key (module_name)=(GEDFact_assistant) already exists.
2022-12-25 11:42:39.394 GMT [14319] webtreesadm@kanoma STATEMENT:  insert into "wt_module" ("module_name", "status") values ($1, $2)
2022-12-25 11:42:39.745 GMT [14333] webtreesadm@kanoma ERROR:  duplicate key value violates unique constraint "wt_module_pkey"
2022-12-25 11:42:39.745 GMT [14333] webtreesadm@kanoma DETAIL:  Key (module_name)=(individual_list) already exists.
2022-12-25 11:42:39.745 GMT [14333] webtreesadm@kanoma STATEMENT:  insert into "wt_module" ("module_name", "status") values ($1, $2)
2022-12-25 11:46:45.668 GMT [14809] webtreesadm@kanoma ERROR:  relation "wt_site_setting" does not exist at character 45
2022-12-25 11:46:45.668 GMT [14809] webtreesadm@kanoma STATEMENT:  select "setting_value", "setting_name" from "wt_site_setting
```
errors on GUI:
```
Undefined property: stdClass::$COALESCE(setting_value, 'media/') …/vendor/illuminate/database/Query/Builder.php:2678
#0 …/vendor/illuminate/database/Query/Builder.php(2678): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/vendor/illuminate/database/Query/Builder.php(2644): Illuminate\Database\Query\Builder->pluckFromObjectColumn()
#2 …/app/Services/MediaFileService.php(377): Illuminate\Database\Query\Builder->pluck()
#3 …/app/Http/RequestHandlers/ManageMediaPage.php(64): Fisharebest\Webtrees\Services\MediaFileService->allMediaFolders()
#4 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ManageMediaPage->handle()
#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#6 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#8 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#10 …/app/Http/Middleware/AuthAdministrator.php(53): Middleland\Dispatcher->handle()
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthAdministrator->process()
#12 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#15 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#16 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#18 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#20 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#22 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#24 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#26 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#27 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#28 …/app/Http/Middleware/UseTransaction.php(44): Illuminate\Database\Connection->transaction()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#30 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#32 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#34 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#36 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#38 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#40 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#42 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#44 …/app/Http/Middleware/BadBotBlocker.php(279): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#46 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#48 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#50 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#51 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#53 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#55 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#57 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#59 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#61 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#63 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#64 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#65 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#66 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#67 {main}
```
There are currently no media files. I check with media.
Appart from that great improvements for postgres in new version! Thanks.

**Comment by fisharebest** [comment]
Is this during setup/install?

Perhaps the process ran twice?  (e.g. press `F5`, or click `next` twice?)

Do you get the same error if you try the installation again?

**Comment by elWyatt** [comment]
I did a fresh install. Installation went smooth. First call to website starts configuration of site, all configuration steps seem to work.
After configuration I see my start page. Without further configuration I click "My page" --> "Control panel" --> "Manage media" and get the above shown error page.

I can run the sql statement from postges log without problem, `select "setting_value", "setting_name" from "wt_site_setting"`  shows valid content. All tables seem to be defined in lowercase:

```
webtest=# \dt
                  Liste der Relationen
 Schema |          Name          |   Typ   | Eigentümer
--------+------------------------+---------+------------
 public | wt_block               | Tabelle | webtest
 public | wt_block_setting       | Tabelle | webtest
 public | wt_change              | Tabelle | webtest
 public | wt_dates               | Tabelle | webtest
 public | wt_default_resn        | Tabelle | webtest
 public | wt_families            | Tabelle | webtest
 public | wt_favorite            | Tabelle | webtest
 public | wt_gedcom              | Tabelle | webtest
 public | wt_gedcom_chunk        | Tabelle | webtest
 public | wt_gedcom_setting      | Tabelle | webtest
 public | wt_hit_counter         | Tabelle | webtest
 public | wt_individuals         | Tabelle | webtest
 public | wt_link                | Tabelle | webtest
 public | wt_log                 | Tabelle | webtest
 public | wt_media               | Tabelle | webtest
 public | wt_media_file          | Tabelle | webtest
 public | wt_message             | Tabelle | webtest
 public | wt_module              | Tabelle | webtest
 public | wt_module_privacy      | Tabelle | webtest
 public | wt_module_setting      | Tabelle | webtest
 public | wt_name                | Tabelle | webtest
 public | wt_news                | Tabelle | webtest
 public | wt_other               | Tabelle | webtest
 public | wt_place_location      | Tabelle | webtest
 public | wt_placelinks          | Tabelle | webtest
 public | wt_places              | Tabelle | webtest
 public | wt_session             | Tabelle | webtest
 public | wt_site_setting        | Tabelle | webtest
 public | wt_sources             | Tabelle | webtest
 public | wt_user                | Tabelle | webtest
 public | wt_user_gedcom_setting | Tabelle | webtest
 public | wt_user_setting        | Tabelle | webtest
(32 Zeilen)
```
Maybe its a case problem from the calling function as I read that mysql is case insensitive whereas postgres "simulates" that by using all lowercase. As php is not currently in my "box of tools" I'm afraid I'm not of much help in debugging code.

To exclude other errors, I run webtrees on a raspberrypi 3 with php 8.2.0, apache 2.4.38 and postgres 11.17

**Comment by fisharebest** [comment]
Maybe.

Try editing line 377 of [app/Services/Media
](https://github.com/fisharebest/webtrees/blob/9e0c35dd30b27012a805a218e71f2f312a1228af/app/Services/MediaFileService.php#L377)

Replace

```
->pluck(new Expression("COALESCE(setting_value, 'media/')"))
```

with

```
->pluck(new Expression("COALESCE(setting_value, 'media/') AS path"))
```

**Comment by elWyatt** [comment]
That fixed the issue. 👍
