### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'setting_value' at row 1 (SQL: insert into `wt_site_setting` (`setting_name`, `setting_value`) values (glide-key, ...

### ISSUE THREAD

**Issue by wirerydr** [fisharebest/webtrees#4693]
## Description

Hello there.  After manually upgrading from 1.7.17 to 2.1.15, I'm now getting errors similar to what I've pasted below, on various pages (this example is for the **default individual**).  It looks like it's hitting a DB column limit or something when trying to write a site-setting called *glide-key*, and it looks like it might be related to some sort of image-display.

I'm having trouble from the output figuring out if a schema upgrade went silently bad, if a module's acting up/deprecated, etc.  Any troubleshooting tips / next-steps would be very greatly appreciated.

Thanks in-advance!

## Environment Details
OS: **Fedora 36 (x86_64)**
Webtrees: **2.1.15**
DB: MariaDB **10.5.16**
PHP Base & Modules:
```
php.x86_64                                  8.1.10-1.fc36                     @updates
php-bcmath.x86_64                           8.1.10-1.fc36                     @updates
php-cli.x86_64                              8.1.10-1.fc36                     @updates
php-common.x86_64                           8.1.10-1.fc36                     @updates
php-fpm.x86_64                              8.1.10-1.fc36                     @updates
php-gd.x86_64                               8.1.10-1.fc36                     @updates
php-gmp.x86_64                              8.1.10-1.fc36                     @updates
php-intl.x86_64                             8.1.10-1.fc36                     @updates
php-mbstring.x86_64                         8.1.10-1.fc36                     @updates
php-mysqlnd.x86_64                          8.1.10-1.fc36                     @updates
php-opcache.x86_64                          8.1.10-1.fc36                     @updates
php-pdo.x86_64                              8.1.10-1.fc36                     @updates
php-pecl-apcu.x86_64                        5.1.21-3.fc36                     @fedora
php-pecl-imagick.x86_64                     3.7.0-2.fc36                      @fedora
php-pecl-zip.x86_64                         1.21.0-1.fc36                     @updates
php-process.x86_64                          8.1.10-1.fc36                     @updates
php-sodium.x86_64                           8.1.10-1.fc36                     @updates
php-xml.x86_64                              8.1.10-1.fc36                     @updates
```

## Debug Log
```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'setting_value' at row 1 (SQL: insert into `wt_site_setting` (`setting_name`, `setting_value`) values (glide-key, 5dc9580f0ffddcff7d2c74a678f5a41b10751a17ae04447f12a2b4dadbd013797f22fc7911acb527c2e48af5573854037a741e1939f580d3cfb8e18a3a6c60af9bd114b87d24dfc36d8052f4dc5940c3cd0e449458781fe2d127f7079952f048c9e60679c90fc6d2f71c24186175602455401a80eb38610a0528a564f6d798bf)) …/vendor/illuminate/database/Connection.php:712
#0 …/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 …/vendor/illuminate/database/Connection.php(502): Illuminate\Database\Connection->run()
#2 …/vendor/illuminate/database/Connection.php(454): Illuminate\Database\Connection->statement()
#3 …/vendor/illuminate/database/Query/Builder.php(2980): Illuminate\Database\Connection->insert()
#4 …/vendor/illuminate/database/Query/Builder.php(3098): Illuminate\Database\Query\Builder->insert()
#5 …/app/Site.php(125): Illuminate\Database\Query\Builder->updateOrInsert()
#6 …/app/MediaFile.php(240): Fisharebest\Webtrees\Site::setPreference()
#7 …/app/MediaFile.php(183): Fisharebest\Webtrees\MediaFile->imageUrl()
#8 …/resources/views/individual-page-images.phtml(37): Fisharebest\Webtrees\MediaFile->displayImage()
#9 …/app/View.php(183): include('...')
#10 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#11 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#12 …/resources/views/individual-page.phtml(53): view()
#13 …/app/View.php(183): include('...')
#14 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#15 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#16 …/app/Http/ViewResponseTrait.php(50): view()
#17 …/app/Http/RequestHandlers/IndividualPage.php(140): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->viewResponse()
#18 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#20 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#22 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#24 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#27 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#28 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#30 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#32 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#34 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#36 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#38 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#39 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#40 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#42 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#44 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#46 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#48 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#50 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#52 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#54 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#56 …/app/Http/Middleware/BadBotBlocker.php(279): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#58 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#60 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#62 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#63 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#65 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#67 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#68 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#69 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#70 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#71 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#72 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#73 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#74 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#75 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#76 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#77 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#78 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#79 {main}
```

**Comment by fisharebest** [comment]
It looks like you have skipped one of the schema update steps.  I'll tell you more when I am back at my computer.

**Comment by wirerydr** [comment]
TYVM for the quick response.  For what it's worth, when I query `wt_log` for messages like `%schema%version%, I get what's shown below.  Right after that, my error messages started appearing.:
```
+--------+---------------------+----------+-----------------------------------------------------------------------------------------+
| log_id | log_time            | log_type | log_message                                     | ip_address      | user_id | gedcom_id |
+--------+---------------------+----------+-----------------------------------------------------------------------------------------+
|   3846 | 2022-12-29 01:21:26 | config   | Site preference "WT_SCHEMA_VERSION" set to "38" | 127.0.0.1       |    NULL |      NULL |
|   3847 | 2022-12-29 01:21:26 | config   | Site preference "WT_SCHEMA_VERSION" set to "39" | 127.0.0.1       |    NULL |      NULL |
|   3848 | 2022-12-29 01:21:26 | config   | Site preference "WT_SCHEMA_VERSION" set to "40" | 127.0.0.1       |    NULL |      NULL |
|   3849 | 2022-12-29 01:21:26 | config   | Site preference "WT_SCHEMA_VERSION" set to "41" | 127.0.0.1       |    NULL |      NULL |
|   3850 | 2022-12-29 01:21:26 | config   | Site preference "WT_SCHEMA_VERSION" set to "42" | 127.0.0.1       |    NULL |      NULL |
|   3851 | 2022-12-29 01:21:26 | config   | Site preference "WT_SCHEMA_VERSION" set to "43" | 127.0.0.1       |    NULL |      NULL |
|   3852 | 2022-12-29 01:21:26 | config   | Site preference "WT_SCHEMA_VERSION" set to "44" | 127.0.0.1       |    NULL |      NULL |
|   3852 | 2022-12-29 01:21:26 | config   | Site preference "WT_SCHEMA_VERSION" set to "45" | 127.0.0.1       |    NULL |      NULL |

**Comment by FrankWarius** [comment]
what is the definition of the column setting_value ?
It should be varchar(2000).
The 'glide-key' insert value in the log has a length of 257

**Comment by fisharebest** [comment]
This column was changed from `VARCHAR(255)` to `VARCHAR(2000)` in the upgrade from webtrees 1.7.2 to 1.7.3.

I don't know why you do not have it.

But you need to change this column definition.  You can use

```
ALTER TABLE `wt_site_setting` CHANGE setting_value setting_value VARCHAR(2000) NOT NULL;
```

**Comment by wirerydr** [comment]
Hmmm:
```
MariaDB [webtrees_1.7.17_upgraded]> describe wt_site_setting;
+---------------+--------------+------+-----+---------+-------+
| Field         | Type         | Null | Key | Default | Extra |
+---------------+--------------+------+-----+---------+-------+
| setting_name  | varchar(32)  | NO   | PRI | NULL    |       |
| setting_value | varchar(255) | NO   |     | NULL    |       |
+---------------+--------------+------+-----+---------+-------+
2 rows in set (0.001 sec)

MariaDB [webtrees_1.7.17_upgraded]>
```
Now, this is a database that I imported from an export-backup of my production 1.7.17 database.  When I go back to that original DB it's also `varchar(255)`.  When I take a look at a freshly-installed 2.1.15 DB instance, I see `varchar(2000)` which makes sense given the contents of `app/Schema/Migration0.php`.  No idea how I reached this state.  The instance is relatively dormant; I last made edits in 2020.

In any event I altered the table as you advised.  The error no longer appears, but images do - awesome.

TYVM for the excellent holiday-season support!  Especially appreciated now that I have 27 new individuals to add as a result of family interviews over the holidays...
