### ISSUE TITLE
Email Settings - cannot update

### ISSUE THREAD

**Issue by borosbence** [fisharebest/webtrees#4707]
When I try to update on the admin panel the email settings I receive the following error:

```
Uncaught Fisharebest\Webtrees\Http\Exceptions\HttpBadRequestException: “route” missing parameter. in /var/www/customers/vh-7309/web/home/webtrees/app/Validator.php:333 
Stack trace: #0 /var/www/customers/vh-7309/web/home/webtrees/resources/views/layouts/default.phtml(69): Fisharebest\Webtrees\Validator->route() #1 /var/www/customers/vh-7309/web/home/webtrees/app/View.php(183): include('...') #2 /var/www/customers/vh-7309/web/home/webtrees/app/View.php(278): Fisharebest\Webtrees\View->render() #3 /var/www/customers/vh-7309/web/home/webtrees/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() #4 /var/www/customers/vh-7309/web/home/webtrees/app/Http/ViewResponseTrait.php(54): view() #5 /var/www/customers/vh-7309/web/home/webtrees/app/Http/Middleware/HandleExceptions.php(171): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->viewResponse() #6 /var/www/customers/vh-7309/web/home/webtrees/app/Http/Middleware/HandleExceptions.php(99): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->httpExceptionResponse() #7 /var/www/customers/vh-7309/web/home/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #8 /var/www/customers/vh-7309/web/home/webtrees/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle() #9 /var/www/customers/vh-7309/web/home/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #10 /var/www/customers/vh-7309/web/home/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #11 /var/www/customers/vh-7309/web/home/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #12 /var/www/customers/vh-7309/web/home/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #13 /var/www/customers/vh-7309/web/home/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #14 /var/www/customers/vh-7309/web/home/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #15 /var/www/customers/vh-7309/web/home/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #16 /var/www/customers/vh-7309/web/home/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #17 /var/www/customers/vh-7309/web/home/webtrees/app/Webtrees.php(275): Middleland\Dispatcher->dispatch() #18 /var/www/customers/vh-7309/web/home/webtrees/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #19 /var/www/customers/vh-7309/web/home/webtrees/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #20 {main} thrown

/var/www/customers/vh-7309/web/home/webtrees/app/Validator.php: 333
```
The same result with Sendmail, SMTP methods. No results in the Website logs. The sendmail is working on the server, fresh Webtrees install.

**Comment by borosbence** [comment]
It seems a translation problem. When I changed the language from hungarian to english it works with SMTP.
