### ISSUE TITLE
Error noted in logs - unable to reproduce

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4845]
A new user had applied for an account and then attempted to login prior to confirming his email address. This error was the next line in the logs. I've attempted and failed to reproduce the error.

======================

Fisharebest\Webtrees\Validator::string():  Argument #1 ($parameter) must be of type string, null given, called in  …/app/Services/CaptchaService.php on line 82 …/app/Validator.php:342 #0 …/app/Services/CaptchaService.php(82):  Fisharebest\Webtrees\Validator-&gt;string(NULL,  &#039;&#039;) #1 …/app/Http/RequestHandlers/RegisterAction.php(103):  Fisharebest\Webtrees\Services\CaptchaService-&gt;isRobot(Object(Nyholm\Psr7\ServerRequest)) #2 …/app/Http/Middleware/RequestHandler.php(52):  Fisharebest\Webtrees\Http\RequestHandlers\RegisterAction-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #4 …/app/Module/CheckForNewVersion.php(122):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Module\CheckForNewVersion-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #6 …/app/Http/Middleware/CheckCsrf.php(80):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #8 …/vendor/oscarotero/middleland/src/Dispatcher.php(118):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #9 …/app/Http/Middleware/Router.php(168):  Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\Router-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #11 …/app/Http/Middleware/BootModules.php(60):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #13 …/app/Http/Middleware/RegisterGedcomTags.php(54):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #15 …/app/Http/Middleware/LoadRoutes.php(75):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #17 …/app/Http/Middleware/CheckForNewVersion.php(57):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #19 …/app/Http/Middleware/UseTransaction.php(45):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #20 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(30):  Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #21 …/app/Http/Middleware/UseTransaction.php(44):  Illuminate\Database\Connection-&gt;transaction(Object(Closure), 3) #22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #23 …/app/Http/Middleware/DoHousekeeping.php(73):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #25 …/app/Http/Middleware/UseTheme.php(68):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #27 …/app/Http/Middleware/CheckForMaintenanceMode.php(51):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #29 …/app/Http/Middleware/UseLanguage.php(71):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #31 …/app/Http/Middleware/UseSession.php(79):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #33 …/app/Http/Middleware/UpdateDatabaseSchema.php(57):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #35 …/app/Http/Middleware/UseDatabase.php(122):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #37 …/app/Http/Middleware/BadBotBlocker.php(288):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #39 …/app/Http/Middleware/CompressResponse.php(73):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #41 …/app/Http/Middleware/ContentLength.php(40):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #43 …/vendor/middlewares/client-ip/src/ClientIp.php(65):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #44 …/app/Http/Middleware/ClientIp.php(47):  Middlewares\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #46 …/app/Http/Middleware/PublicFiles.php(62):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\PublicFiles-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #48 …/app/Http/Middleware/HandleExceptions.php(90):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #50 …/app/Http/Middleware/BaseUrl.php(73):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #52 …/app/Http/Middleware/ReadConfigIni.php(68):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #54 …/app/Http/Middleware/SecurityHeaders.php(48):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #56 …/app/Http/Middleware/EmitResponse.php(57):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):  Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest),  Object(Middleland\Dispatcher)) #58 …/vendor/oscarotero/middleland/src/Dispatcher.php(118):  Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #59 …/app/Webtrees.php(284):  Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #60 …/app/Webtrees.php(252):  Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #61 …/index.php(32): Fisharebest\Webtrees\Webtrees-&gt;run() #62 {main}

**Comment by fisharebest** [comment]
Was this a genuine human registration, or could it have been a robot?

**Comment by ddrury** [comment]
It was a genuine person who subsequently completed his application and I've authorised him

**Comment by fisharebest** [comment]
This is a duplicate.  I can't find the other one, but I closed it a few days ago, as it was fixed by another change made a couple of years ago...
