### ISSUE TITLE
Error enabling historic events

### ISSUE THREAD

**Issue by gregoiregentil** [fisharebest/webtrees#4880]
Congratulations for all the work. It's an amazing php software.

I'm on 2.1.17. When I enable "Faits historiques de France" in Historic events, I get the following error. Any idea what's wrong?

```
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x87\xAB\xF0\x9F...' for column 'session_data' at row 1 (SQL: update `session` set `session_data` = initiated|b:1;_GUEST_sessiontime|s:10:"1695591394";language|s:5:"en-US";theme|s:8:"webtrees";last_gedcom_id|i:1;last_page_name|s:14:"individual.php";last_page_parameter|s:2:"I1";last_count|i:71;CSRF_TOKEN|s:32:"lwgkdj6CLwQLfsr4CLD8yhITtXcl7tW0";wt_user|i:1;flash_messages|a:2:{i:0;O:8:"stdClass":2:{s:4:"text";s:71:"The module “Faits historiques de France 🇫🇷” has been enabled.";s:6:"status";s:7:"success";}i:1;O:8:"stdClass":2:{s:4:"text";s:42:"The website preferences have been updated.";s:6:"status";s:7:"success";}} where `session_id` = 6kl4ikvtc8ir4q6rtg5o230ssn) …/vendor/illuminate/database/Connection.php:712
#0 …/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 …/vendor/illuminate/database/Connection.php(533): Illuminate\Database\Connection->run()
#2 …/vendor/illuminate/database/Connection.php(466): Illuminate\Database\Connection->affectingStatement()
#3 …/vendor/illuminate/database/Query/Builder.php(3063): Illuminate\Database\Connection->update()
#4 …/app/SessionDatabaseHandler.php(125): Illuminate\Database\Query\Builder->update()
#5 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write()
#6 …/app/Session.php(100): session_write_close()
#7 …/app/Http/Middleware/UseSession.php(80): Fisharebest\Webtrees\Session::save()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#9 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#11 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#13 …/app/Http/Middleware/BadBotBlocker.php(287): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#15 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#17 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#19 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#20 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#22 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#24 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#26 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#28 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#30 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#33 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#34 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#35 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#36 {main}
```

**Comment by fisharebest** [comment]
You have added a 4-byte UTF-8 character.  Probably an emoji or flag.

There is currently an open issue (#2950) to convert webtrees from 3-byte UTF-8 to 4-byte UTF-8.

This is currently in progress.  The difficulty is that depending on the history of your site, the exact structure of your database is unknown (e.g. index names, foreign keys, etc.).  Our database library assumes you know the exact structure.

So, I need to convert all the database migrations (and possibly the rest of the database abstraction layer) to use doctrine/dbal instead of illuminate/database.

**Comment by gregoiregentil** [comment]
I'm 100% sure that I didn't import an emoji in my gedcom. And I'm exporting - re-importing frequently my gedcom file and I know its content.

It might be a stupid suggestion but the problem might come from the history event itself with its title:

“Faits historiques de France 🇫🇷”

\xF0\x9F\x87\xAB\xF0\x9F... in the error message is actually the French flag.

**Comment by fisharebest** [comment]
> It might be a stupid suggestion but the problem might come from the history event itself with its title:
> “Faits historiques de France 🇫🇷”

This should not be a problem.  This value is not stored in the database - only displayed.

I just enabled the french historic events on my dev machine and also on the demo site - and do not get any errors.

The error message says that this data is being stored in the "session data".

Could you have used the clippings cart to copy something?  There isn't much else stored in the session.

**Comment by fisharebest** [comment]
The data isn't in the database.  webtrees attempted to write the data to the database, but MySQL rejected it.

**Comment by fisharebest** [comment]
Is this the module that is supplied with webtrees, or is it a third-party one?

Do you have any other third-party modules installed?

**Comment by gregoiregentil** [comment]
No third-party module.

![Screenshot from 2023-09-25 12-05-33](https://github.com/fisharebest/webtrees/assets/486156/dc336291-f026-4c48-8f1c-d4d8a3d7e5ab)

**Comment by ric2016** [comment]
> This should not be a problem. This value is not stored in the database - only displayed.

The original stack trace clearly shows that the module title is definitely stored in the database, as part of the session data, via the flash messages:

`flash_messages|a:2:{i:0;O:8:"stdClass":2:{s:4:"text";s:71:"The module “Faits historiques de France 🇫🇷” has been enabled."`

**Comment by gregoiregentil** [comment]
I have done something very stupid: I went to the php file and removed that damned flag. Problem solved! The error disappears. It seems to make sense. When enabling, the title is copied in the session row in the database the 4-byte creates the problem.

Now, where do those "faits historiques" appear? Because I don't see them anywhere. That was my initial objective to understand what this feature is about...

**Comment by fisharebest** [comment]
These facts are shown on the individuals "Facts and events" tab - but only when you use the French language.

What version of MySQL/MariaDB do you use?

**Comment by gregoiregentil** [comment]
At last, I see the events!!! I was in English language though I'm French.

> mysql --version
> mysql  Ver 8.0.34-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

So to recap the situation, I can make it work by removing the flag (4-byte character) in the php file.

**Comment by fisharebest** [comment]
Can you run this SQL statement for me

`SHOW CREATE TABLE wt_session;`

Originally, the column `session_data` was `LONGBLOB`.  Recently, it changed to `LONGTEXT`.
This was to support SQL-Server.

A `LONGBLOB` column will accept the 4-byte UTF8 characters.
A `LONGTEXT` column will give the error that you see.

So, the error depends on when you created your database.
Older installations will work OK.
Newer installations will have this error.

I am currently working on an update from `utf8mb3` to `utf8mb4` - which will fix this problem.
Until then, you should be able to fix it locally by changing the column from `LONGTEXT` to `LONGBLOB`;
You can do this with the following SQL statement:

`ALTER TABLE wt_session CHANGE session_data session_data LONGBLOB;`

**Comment by gregoiregentil** [comment]
Did you mean?

> describe session;

It's longtext

> mysql> describe session;
> +--------------+-------------+------+-----+-------------------+-------------------+
> | Field        | Type        | Null | Key | Default           | Extra             |
> +--------------+-------------+------+-----+-------------------+-------------------+
> | session_id   | varchar(32) | NO   | PRI | NULL              |                   |
> | session_time | timestamp   | NO   | MUL | CURRENT_TIMESTAMP | DEFAULT_GENERATED |
> | user_id      | int         | NO   | MUL | NULL              |                   |
> | ip_address   | varchar(45) | NO   |     | NULL              |                   |
> | session_data | longtext    | NO   |     | NULL              |                   |
> +--------------+-------------+------+-----+-------------------+-------------------+
> 5 rows in set (0.04 sec)

**Comment by fisharebest** [comment]
OK - as I guessed.

Alter this column and it should fix your problem.

**Comment by gregoiregentil** [comment]
Thank you for your help. I let you close the bug and modify the code of the table creation if you think it's appropriate.

Once again, really great software!

**Comment by durangod** [comment]
Hi, i was just curious why you dont use utf8mb4_unicode_520_ci when you upgrade the db, isnt that the new standard for international acceptance?   Is that because of possible legacy issue?

And i agree great software.  I am sure you dont hear this enough, thank you so much :)
