### ISSUE TITLE
2.2 Dev MS SQL Server Error display log - Sys- and Webtrees lamguage is DE

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4933]
date/time "2023-12-31 16:54:49.453" does not match pattern "Y-m-d H:i:s" …\app\Factories\TimestampFactory.php:68
#0 …\app\Http\RequestHandlers\SiteLogsPage.php(71): Fisharebest\Webtrees\Factories\TimestampFactory->fromString()
#1 …\app\Http\Middleware\RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\SiteLogsPage->handle()
#2 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#3 …\app\Module\HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#4 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#5 …\app\Module\CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
#6 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#7 …\app\Http\Middleware\AuthAdministrator.php(53): Middleland\Dispatcher->handle()
#8 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthAdministrator->process()
#9 …\app\Http\Middleware\CheckCsrf.php(80): Middleland\Dispatcher->handle()
#10 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#11 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle()
#12 …\app\Webtrees.php(275): Middleland\Dispatcher->dispatch()
#13 …\app\Http\Middleware\Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch()
#14 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#15 …\app\Http\Middleware\BootModules.php(60): Middleland\Dispatcher->handle()
#16 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#17 …\app\Http\Middleware\RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#18 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#19 …\app\Http\Middleware\LoadRoutes.php(75): Middleland\Dispatcher->handle()
#20 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#21 …\app\Http\Middleware\CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#22 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#23 …\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher->handle()
#24 …\vendor\illuminate\database\Concerns\ManagesTransactions.php(30): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#25 …\vendor\illuminate\database\SqlServerConnection.php(30): Illuminate\Database\Connection->transaction()
#26 …\app\Http\Middleware\UseTransaction.php(44): Illuminate\Database\SqlServerConnection->transaction()
#27 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#28 …\app\Http\Middleware\DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#29 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#30 …\app\Http\Middleware\UseTheme.php(69): Middleland\Dispatcher->handle()
#31 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#32 …\app\Http\Middleware\CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#33 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#34 …\app\Http\Middleware\UseLanguage.php(71): Middleland\Dispatcher->handle()
#35 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#36 …\app\Http\Middleware\UseSession.php(78): Middleland\Dispatcher->handle()
#37 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#38 …\app\Http\Middleware\UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#39 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#40 …\app\Http\Middleware\UseDatabase.php(126): Middleland\Dispatcher->handle()
#41 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#42 …\app\Http\Middleware\BadBotBlocker.php(282): Middleland\Dispatcher->handle()
#43 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#44 …\app\Http\Middleware\CompressResponse.php(73): Middleland\Dispatcher->handle()
#45 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#46 …\app\Http\Middleware\ContentLength.php(40): Middleland\Dispatcher->handle()
#47 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#48 …\vendor\middlewares\client-ip\src\ClientIp.php(65): Middleland\Dispatcher->handle()
#49 …\app\Http\Middleware\ClientIp.php(47): Middlewares\ClientIp->process()
#50 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#51 …\app\Http\Middleware\HandleExceptions.php(90): Middleland\Dispatcher->handle()
#52 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#53 …\app\Http\Middleware\BaseUrl.php(73): Middleland\Dispatcher->handle()
#54 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#55 …\app\Http\Middleware\ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#56 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#57 …\app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#58 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#59 …\app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher->handle()
#60 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#61 …\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle()
#62 …\app\Webtrees.php(275): Middleland\Dispatcher->dispatch()
#63 …\app\Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#64 …\index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#65 {main}

**Comment by FrankWarius** [comment]
duplicate to #4682
