### ISSUE TITLE
Missing module causes site to be unreachable

### ISSUE THREAD

**Issue by iamdoubz** [fisharebest/webtrees#4955]
Upgraded from version 2.1.16 to 2.1.18. After doing an "auto" upgrade, I am presented with the below error.

## Investigation

In `App\Module` in version 16, there is a file called `OrdnanceSurveyHistoricMaps.php` which I do not use. In versions 17 and 18, it is no longer there.

## My Fix

Downloaded the 2.1.16 release, and dropped the missing file in the `App\Module` directory, no more error.

**Error Log:**

```
Target class [Fisharebest\Webtrees\Module\OrdnanceSurveyHistoricMaps] does not exist. …/vendor/illuminate/container/Container.php:879 #0 …/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container-&gt;build() #1 …/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container-&gt;resolve() #2 …/app/Webtrees.php(312): Illuminate\Container\Container-&gt;make() #3 …/app/Helpers/functions.php(43): Fisharebest\Webtrees\Webtrees::make() #4 …/app/Services/ModuleService.php(662): app() #5 [internal function]: Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}() #6 …/vendor/illuminate/collections/Collection.php(695): array_map() #7 …/app/Services/ModuleService.php(661): Illuminate\Support\Collection-&gt;map() #8 …/app/Services/ModuleService.php(616): Fisharebest\Webtrees\Services\ModuleService-&gt;coreModules() #9 …/app/Cache.php(60): Fisharebest\Webtrees\Services\ModuleService-&gt;Fisharebest\Webtrees\Services\{closure}() #10 …/vendor/symfony/cache/Adapter/ArrayAdapter.php(84): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}() #11 …/app/Cache.php(57): Symfony\Component\Cache\Adapter\ArrayAdapter-&gt;get() #12 …/app/Services/ModuleService.php(607): Fisharebest\Webtrees\Cache-&gt;remember() #13 …/app/Services/ModuleService.php(573): Fisharebest\Webtrees\Services\ModuleService-&gt;all() #14 …/app/Http/Middleware/UseLanguage.php(84): Fisharebest\Webtrees\Services\ModuleService-&gt;findByInterface() #15 …/app/Http/Middleware/UseLanguage.php(63): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;languages() #16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() #17 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher-&gt;handle() #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() #19 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle() #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() #21 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher-&gt;handle() #22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() #23 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher-&gt;handle() #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() #25 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher-&gt;handle() #26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() #27 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle() #28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process() #29 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle() #30 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() #32 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle() #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() #34 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher-&gt;handle() #35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() #36 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle() #37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process() #38 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle() #39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() #40 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() #41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() #42 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #43 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch() #44 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #45 …/index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #46 {main}

```

# My question

How do I make sure this doesn't happen when I upgrade to 19 and beyond? Thank you for a wonderful tool and all of your hard work.

**Comment by fisharebest** [comment]
The "Obvious" explanation for this is that the upgrade was incomplete, and that you have a mixture of files from 2.1.16 and 2.1.18

Do you still see this error on your site?  It would be helpful to have an environment where it can be reproduced and examined.

**Comment by iamdoubz** [comment]
I performed the upgrade through the web interface so I didn't think this would happen. But, now that you mention it, I did change my apache2 conf file to use php8.2-fpm from 8.0. Maybe it was stuck in cache and all I needed to do was restart fpm. But, no, the error is not on my site anymore after adding in the file.

I also was very bad and did _not_ do a back up first.

It was probably a fluke deal or I'm guessing more people would have logged errors back in version 2.1.17...

**Comment by fisharebest** [comment]
> change my apache2 conf file to use php8.2-fpm from 8.0. Maybe it was stuck in cache and all I needed to do was restart fpm

That's a plausible explanation.  And about the only one I can think of.

In which case, I'll close this issue as there's nothing I can really do about it.  But thanks for reporting.
