### ISSUE TITLE
Main branch: Trying to compile language files with latest code fails in composer webtrees:build

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4980]
> php index.php compile-po-files
```
PHP Fatal error:  Uncaught RuntimeException: could not find driver in /mnt/d/Server/html/webtrees-2.2/app/DB.php:128
Stack trace:
#0 /mnt/d/Server/html/webtrees-2.2/app/Cli/Console.php(64): Fisharebest\Webtrees\DB::connect()
#1 /mnt/d/Server/html/webtrees-2.2/app/Webtrees.php(261): Fisharebest\Webtrees\Cli\Console->bootstrap()
#2 /mnt/d/Server/html/webtrees-2.2/app/Webtrees.php(248): Fisharebest\Webtrees\Webtrees->cliRequest()
#3 /mnt/d/Server/html/webtrees-2.2/index.php(24): Fisharebest\Webtrees\Webtrees->run()
#4 {main}
  thrown in /mnt/d/Server/html/webtrees-2.2/app/DB.php on line 128
```

**Comment by fisharebest** [comment]
It works for me.  Is the rest of the site running OK?

**Comment by ddrury** [comment]
When I engaged my brain the problem was obvious. I'm using wamp on windows to serve webtrees but Ubuntu on wsl2 for running composer, npm etc. and of course by default the wsl/ubuntu config doesn't see windows. Using windows powershell runs fine
