### ISSUE TITLE
Registry::container()->get($id) throws an exception if the interface cannot be found

### ISSUE THREAD

**Issue by Jefferson49** [fisharebest/webtrees#5072]
Observed with webtrees 2.2.1

The newly added **Registry::container()->get($id)** throws an exception if the interface cannot be found:
```
ReflectionException: Class "Cissee\WebtreesExt\MoreI18N" does not exist in C:\wamp64\www\webtrees\app\Container.php:81
Stack trace:
#0 C:\wamp64\www\webtrees\app\Container.php(81): ReflectionClass->__construct('Cissee\\Webtrees...')
#1 C:\wamp64\www\webtrees\app\Container.php(58): Fisharebest\Webtrees\Container->make('Cissee\\Webtrees...') 
```

Shouldn't this exception be caught and get($id) could return null instead?

**Comment by fisharebest** [comment]
I think throwing an exception is the correct action.

The [container specification](https://www.php-fig.org/psr/psr-11/) lists specific exceptions that should be thrown.

> return null instead?

Containers can contain any type of object - including `NULL`.  At present, we only store objects in it, but this could always change.
