### ISSUE TITLE
Error in  the pending changes webtree ver 2.1.22

### ISSUE THREAD

**Issue by borjian** [fisharebest/webtrees#5090]
Hello, after editing the site by one of the site users who had the role of editor on the site. When I logged in as an administrator, I saw the following error. After confirming the pending changes, the error was fixed. What is the reason?

Call to a member function canShow() on null …/app/Module/ReviewChangesModule.php:179 #0 …/resources/views/user-page-block.phtml(20): Fisharebest\Webtrees\Module\ReviewChangesModule-&gt;getBlock(Object(Fisharebest\Webtrees\Tree), 139, &#039;user&#039;) #1 …/app/View.php(183): include(&#039;/home3/borjtree...&#039;) #2 …/app/View.php(278): Fisharebest\Webtrees\View-&gt;render() #3 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make(&#039;user-page-block&#039;, Array) #4 …/resources/views/user-page.phtml(30): view(&#039;user-page-block&#039;, Array) #5 …/app/View.php(183): include(&#039;/home3/borjtree...&#039;) #6 …/app/View.php(278): Fisharebest\Webtrees\View-&gt;render() #7 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make(&#039;user-page&#039;, Array) #8 …/app/Http/ViewResponseTrait.php(50): view(&#039;user-page&#039;, Array) #9 …/app/Http/RequestHandlers/UserPage.php(80): Fisharebest\Webtrees\Http\RequestHandlers\UserPage-&gt;viewResponse(&#039;user-page&#039;, Array) #10 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\UserPage-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #12 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #14 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #16 …/app/Http/Middleware/AuthLoggedIn.php(51): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthLoggedIn-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #18 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #21 …/app/Webtrees.php(276): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #22 …/app/Http/Middleware/Router.php(163): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #24 …/app/Http/Middleware/BootModules.php(58): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #26 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #30 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #33 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #34 …/app/Http/Middleware/UseTransaction.php(44): Illuminate\Database\Connection-&gt;transaction(Object(Closure), 3) #35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #36 …/app/Http/Middleware/DoHousekeeping.php(71): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #38 …/app/Http/Middleware/UseTheme.php(67): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #40 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #42 …/app/Http/Middleware/UseLanguage.php(69): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #44 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #46 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #48 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #50 …/app/Http/Middleware/BadBotBlocker.php(308): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #52 …/app/Http/Middleware/CompressResponse.php(71): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #54 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #56 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #57 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #59 …/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #61 …/app/Http/Middleware/SecurityHeaders.php(49): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #63 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #65 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #67 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #68 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #69 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #70 …/app/Webtrees.php(276): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #71 …/app/Webtrees.php(263): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #72 …/index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #73 {main}

**Comment by fisharebest** [comment]
With pending changes, we keep a copy of the old and new data.

When we create new records, the "old" data is NULL.
When we delete records, the "new" data is NULL.

It shouldn't be possible for both "old" and "new" to be NULL at the same time.
But if they are, then it would give the error that you see.

I can't think of any explanation for how this has happened on your site.

Can your editor give any extra information?

**Comment by borjian** [comment]
thanks Unfortunately, I could not understand anything about the editor and the type of operation. In the subsequent changes that were made in the information, this has not happened again
